#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════╗
║      Enterprise AI Agent — Web Setup Wizard v3.0                    ║
║                                                                      ║
║  Started automatically by setup.py --web                            ║
║  Or manually: uvicorn setup_web:app --host 0.0.0.0 --port 8088      ║
╚══════════════════════════════════════════════════════════════════════╝
"""
from __future__ import annotations

import json
import os
import re
import secrets
import shutil
import urllib.parse
from datetime import datetime
from pathlib import Path
from typing import Any

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse

# ── Paths ─────────────────────────────────────────────────────────────────
BASE_DIR    = Path(__file__).parent.resolve()
CONFIG_DIR  = BASE_DIR / "config"
CONFIG_DIR.mkdir(exist_ok=True)
ENV_FILE    = BASE_DIR / ".env"
SETTINGS_FILE = BASE_DIR / "settings.json"
SETTINGS_CFG  = CONFIG_DIR / "settings.json"
SCHEMA_FILE   = CONFIG_DIR / "accounting_schema.json"
BACKUP_DIR    = BASE_DIR / "backups"

# ── App ───────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Enterprise AI Agent — Web Setup",
    version="3.0",
    docs_url=None,
    redoc_url=None,
)

# ── In-memory session store ───────────────────────────────────────────────
sessions: dict[str, dict[str, Any]] = {}

STEPS = {
    "en": ["Language", "LLM", "Identity", "Security", "Channels", "Database", "Permissions", "Finalize"],
    "ar": ["اللغة", "النموذج", "الهوية", "الأمان", "القنوات", "قاعدة البيانات", "الصلاحيات", "الإنهاء"],
}

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  Utility                                                                 ║
# ╚══════════════════════════════════════════════════════════════════════════╝

def _session(request: Request) -> tuple[str, dict]:
    sid = request.cookies.get("setup_sid") or secrets.token_hex(20)
    if sid not in sessions:
        sessions[sid] = {}
    return sid, sessions[sid]


def _load_existing_env() -> dict[str, str]:
    env: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def _load_existing_settings() -> dict:
    for p in (SETTINGS_CFG, SETTINGS_FILE):
        if p.exists():
            try:
                return json.loads(p.read_text(encoding="utf-8"))
            except Exception:
                pass
    return {}


def _load_existing_schema() -> dict:
    if SCHEMA_FILE.exists():
        try:
            return json.loads(SCHEMA_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def _write_env(env_vars: dict[str, str]) -> None:
    lines = [
        "# Enterprise AI Agent — Environment Variables",
        f"# Generated by Web Setup: {datetime.now().isoformat()}",
        "# Do NOT commit this file to version control.",
        "",
    ]
    for k, v in sorted(env_vars.items()):
        if v:
            if any(c in str(v) for c in (" ", "#", "&", ";")):
                lines.append(f'{k}="{v}"')
            else:
                lines.append(f"{k}={v}")
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_settings(settings: dict) -> None:
    payload = json.dumps(settings, indent=2, ensure_ascii=False)
    SETTINGS_FILE.write_text(payload, encoding="utf-8")
    SETTINGS_CFG.write_text(payload, encoding="utf-8")


def _write_schema(schema: dict) -> None:
    SCHEMA_FILE.write_text(json.dumps(schema, indent=2, ensure_ascii=False), encoding="utf-8")


def _backup() -> str:
    BACKUP_DIR.mkdir(exist_ok=True)
    ts  = datetime.now().strftime("%Y%m%d_%H%M%S")
    dst = BACKUP_DIR / f"web_backup_{ts}"
    dst.mkdir(exist_ok=True)
    for f in (ENV_FILE, SETTINGS_FILE, SETTINGS_CFG, SCHEMA_FILE):
        if f.exists():
            shutil.copy2(f, dst / f.name)
    return str(dst)


# ── Connection string builder ─────────────────────────────────────────────

def _build_url(form: dict) -> str:
    db_type  = form.get("db_type", "mssql")
    if db_type == "sqlite":
        return f"sqlite:///{form.get('sqlite_path', 'data/accounting.db')}"

    host    = form.get("host", "localhost")
    port    = form.get("port", "1433")
    db_name = form.get("db_name", "")
    user    = form.get("username", "")
    pw      = urllib.parse.quote_plus(form.get("password", ""))
    user_at = f"{user}:{pw}@" if user else ""

    drv_map = {
        "oracle":     "oracle+oracledb",
        "mssql":      "mssql+pyodbc",
        "mysql":      "mysql+pymysql",
        "postgresql": "postgresql+psycopg2",
    }
    drv = drv_map.get(db_type, "oracle+oracledb")

    if db_type == "mssql":
        odbc = urllib.parse.quote_plus(form.get("odbc_driver", "ODBC Driver 18 for SQL Server"))
        return f"{drv}://{user_at}{host}:{port}/{db_name}?driver={odbc}&TrustServerCertificate=yes"
    if db_type == "oracle":
        service = db_name or "ORCL"
        return f"{drv}://{user_at}{host}:{port}/?service_name={service}"
    return f"{drv}://{user_at}{host}:{port}/{db_name}"


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  API Endpoints                                                           ║
# ╚══════════════════════════════════════════════════════════════════════════╝

@app.get("/", response_class=HTMLResponse)
async def root():
    return RedirectResponse(url="/setup")


@app.get("/setup", response_class=HTMLResponse)
async def setup_home(request: Request, step: int = 0, lang: str = "en"):
    sid, sess = _session(request)
    if lang not in STEPS:
        lang = "en"
    step = max(0, min(step, 8))

    # Pre-fill session with existing config on first visit
    if not sess:
        sessions[sid] = {
            "env":      _load_existing_env(),
            "settings": _load_existing_settings(),
            "schema":   _load_existing_schema(),
        }

    step_names = STEPS[lang]
    context = {
        "lang":         lang,
        "step":         step,
        "total_steps":  8,
        "step_names":   step_names,
        "step_title":   step_names[step] if step < len(step_names) else "Complete",
        "session":      json.dumps(sessions.get(sid, {}), ensure_ascii=False, indent=2),
        "admin_key":    secrets.token_urlsafe(40),
        "user_key":     secrets.token_urlsafe(40),
        "jwt_secret":   secrets.token_urlsafe(40),
        "enc_key":      secrets.token_urlsafe(40),
        "existing_env": sessions.get(sid, {}).get("env", {}),
    }
    html = _render_setup_page(context)
    resp = HTMLResponse(html)
    resp.set_cookie("setup_sid", sid, max_age=7200, httponly=True)
    return resp


@app.post("/setup")
async def handle_step(request: Request, step: int = 0, lang: str = "en"):
    sid, sess = _session(request)
    form = dict(await request.form())
    sess[f"step_{step}"] = form

    next_step = step + 1
    if next_step >= 8:
        await _finalize(sid)
        return RedirectResponse(url=f"/setup?step=8&lang={lang}", status_code=303)
    return RedirectResponse(url=f"/setup?step={next_step}&lang={lang}", status_code=303)


# ── API: test LLM connection ──────────────────────────────────────────────

@app.post("/api/test/llm")
async def test_llm(request: Request):
    form = dict(await request.form())
    url  = form.get("url", "").rstrip("/")
    try:
        import urllib.request as ur
        req = ur.Request(f"{url}/api/tags", headers={"User-Agent": "EnterpriseAI-Setup/3.0"})
        with ur.urlopen(req, timeout=6) as r:
            body = json.loads(r.read())
            models = [m["name"] for m in body.get("models", [])[:5]]
            return JSONResponse({"ok": True, "message": f"Connected · {len(body.get('models', []))} models", "models": models})
    except Exception as e:
        return JSONResponse({"ok": False, "message": str(e)})


# ── API: test database connection ─────────────────────────────────────────

@app.post("/api/test/db")
async def test_db(request: Request):
    form = dict(await request.form())

    # Support passing full URL or building from fields
    full_url = form.get("db_url", "").strip()
    if not full_url:
        full_url = _build_url(form)

    try:
        from sqlalchemy import create_engine, text  # type: ignore
        # Oracle's driver does not accept the pyodbc-style "timeout" connect arg
        connect_args = {} if full_url.startswith("oracle") else {"timeout": 8}
        engine = create_engine(full_url, connect_args=connect_args, pool_pre_ping=True)
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        engine.dispose()
        return JSONResponse({"ok": True, "message": "Connection successful", "url": full_url})
    except ImportError:
        return JSONResponse({"ok": False, "message": "SQLAlchemy not installed. Run: pip install sqlalchemy"})
    except Exception as e:
        return JSONResponse({"ok": False, "message": str(e), "url": full_url})


# ── API: auto-discover database schema ───────────────────────────────────

@app.post("/api/discover/db")
async def discover_db(request: Request):
    form = dict(await request.form())
    full_url = form.get("db_url", "").strip() or _build_url(form)

    try:
        from sqlalchemy import create_engine, inspect as sa_inspect  # type: ignore
        engine = create_engine(full_url)
        inspector = sa_inspect(engine)
        tables_raw = inspector.get_table_names()
        result: dict[str, Any] = {}
        for tbl in tables_raw:
            try:
                cols = inspector.get_columns(tbl)
                result[tbl] = {
                    "table":   tbl,
                    "columns": {c["name"].lower(): c["name"] for c in cols},
                }
            except Exception:
                continue
        engine.dispose()
        return JSONResponse({"ok": True, "tables_count": len(result), "tables": result})
    except ImportError:
        return JSONResponse({"ok": False, "message": "SQLAlchemy not installed"})
    except Exception as e:
        return JSONResponse({"ok": False, "message": str(e)})


# ── API: build connection URL preview ────────────────────────────────────

@app.post("/api/build-url")
async def build_url_endpoint(request: Request):
    form = dict(await request.form())
    url  = _build_url(form)
    return JSONResponse({"url": url})


# ── Finalize ──────────────────────────────────────────────────────────────

async def _finalize(sid: str) -> None:
    data = sessions.get(sid, {})

    env_vars:  dict[str, str] = {}
    settings:  dict[str, Any] = {"version": 4, "setup_completed_at": datetime.now().isoformat()}
    schema:    dict[str, Any] = {"version": 2, "databases": {}}

    # ── Merge all step data ──────────────────────────────────────────────
    for step_key in sorted(data.keys()):
        if not step_key.startswith("step_"):
            continue
        step_data: dict = data[step_key]

        # Step 0: language
        if step_key == "step_0":
            settings.setdefault("agent", {})["language"] = step_data.get("language", "en")

        # Step 1: LLM
        elif step_key == "step_1":
            provider  = step_data.get("provider", "ollama")
            model     = step_data.get("model", "qwen2.5:7b")
            base_url  = step_data.get("base_url", "http://localhost:11434")
            api_key   = step_data.get("api_key", "")
            prefix_map = {
                "ollama": "ollama", "openai": "openai", "anthropic": "openai",
                "google": "openai", "deepseek": "openai", "custom": "openai",
            }
            env_vars["DEFAULT_MODEL"]   = f"{prefix_map.get(provider, 'ollama')}:{model}"
            env_vars["OPENAI_BASE_URL"] = base_url
            env_vars["OLLAMA_BASE_URL"] = base_url if provider == "ollama" else "http://localhost:11434"
            if api_key:
                env_vars["OPENAI_API_KEY"] = api_key
            settings["llm_provider"] = provider
            settings["llm_model"]    = model

        # Step 2: Identity
        elif step_key == "step_2":
            settings.setdefault("agent", {}).update({
                "name":           step_data.get("agent_name", "Enterprise AI Agent"),
                "personality":    step_data.get("personality", "a professional enterprise assistant"),
                "reply_language": step_data.get("reply_language", "auto"),
            })

        # Step 3: Security
        elif step_key == "step_3":
            admin_key = step_data.get("admin_key", secrets.token_urlsafe(40))
            user_key  = step_data.get("user_key",  secrets.token_urlsafe(40))
            env_vars["ADMIN_KEY"]      = admin_key
            env_vars["USER_KEY"]       = user_key
            env_vars["API_KEYS"]       = f"admin:{admin_key},user:{user_key}"
            env_vars["JWT_SECRET"]     = step_data.get("jwt_secret",  secrets.token_urlsafe(40))
            env_vars["ENCRYPTION_KEY"] = step_data.get("enc_key",     secrets.token_urlsafe(40))

        # Step 4: Channels
        elif step_key == "step_4":
            channels: dict[str, Any] = {}
            port = int(step_data.get("web_port", 8000))
            channels["web"] = {"enabled": True, "port": port}
            if step_data.get("whatsapp_enabled") == "on":
                channels["whatsapp"] = {"enabled": True, "prefix": step_data.get("whatsapp_prefix", "!")}
            else:
                channels["whatsapp"] = {"enabled": False}
            if step_data.get("telegram_enabled") == "on":
                tok = step_data.get("telegram_token", "")
                if tok:
                    env_vars["TELEGRAM_BOT_TOKEN"] = tok
                channels["telegram"] = {"enabled": bool(tok)}
            else:
                channels["telegram"] = {"enabled": False}
            # SMTP
            if step_data.get("smtp_enabled") == "on":
                for k in ("smtp_server", "smtp_port", "smtp_user", "smtp_pass", "smtp_from"):
                    v = step_data.get(k, "")
                    if v:
                        env_vars[k.upper()] = v
            settings["channels"] = channels

        # Step 5: Database
        elif step_key == "step_5":
            if step_data.get("accounting_enabled") == "on":
                db_key     = re.sub(r"[^a-z0-9_]", "_", step_data.get("db_key", "onyxdb").lower())
                db_name    = step_data.get("db_display_name", db_key)
                db_url     = step_data.get("db_url", "").strip() or _build_url(step_data)
                tables_raw = step_data.get("discovered_tables", "")

                try:
                    tables: dict = json.loads(tables_raw) if tables_raw else {}
                except Exception:
                    tables = {}

                schema["databases"][db_key] = {
                    "name":          db_name,
                    "db_url":        db_url,
                    "enabled":       True,
                    "tables":        tables,
                    "query_aliases": {},
                }
                env_vars["ACCOUNTING_DB_URL"] = db_url

                allowed_queries = [
                    q for q in [
                        "sales_summary", "revenue_by_month", "top_customers",
                        "expenses_summary", "invoice_lookup", "cash_balance",
                        "vendor_balances", "sales_by_item",
                    ]
                    if step_data.get(f"allow_{q}") == "on"
                ]
                settings["accounting"] = {
                    "enabled":         True,
                    "read_only":       True,
                    "allowed_queries": allowed_queries,
                }
            else:
                settings["accounting"] = {"enabled": False}

        # Step 6: Permissions
        elif step_key == "step_6":
            perm_keys = [
                "web_search", "calculator", "get_current_time", "read_file",
                "knowledge_rag", "accounting_tools", "generate_report",
                "list_reports", "search_conversations", "send_email", "send_webhook",
            ]
            settings["permissions"] = {k: (step_data.get(k) == "on") for k in perm_keys}

    # ── Backup + write ────────────────────────────────────────────────────
    _backup()
    _write_env(env_vars)
    _write_settings(settings)
    if schema["databases"]:
        _write_schema(schema)


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  HTML Renderer (single-page, no Jinja2 dependency)                       ║
# ╚══════════════════════════════════════════════════════════════════════════╝

def _render_setup_page(ctx: dict) -> str:
    step       = ctx["step"]
    lang       = ctx["lang"]
    total      = ctx["total_steps"]
    step_names = ctx["step_names"]
    pct        = int(100 * step / total)
    rtl        = "rtl" if lang == "ar" else "ltr"
    font_url   = "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
    is_done    = step >= total

    # Step content
    content = _step_content(step, ctx)

    # Sidebar steps
    sidebar_items = ""
    for i, name in enumerate(step_names):
        if i < step:
            cls  = "done"
            icon = "✓"
        elif i == step:
            cls  = "active"
            icon = str(i + 1)
        else:
            cls  = ""
            icon = str(i + 1)
        sidebar_items += f'<div class="step-item {cls}"><div class="step-num">{icon}</div><div class="step-label">{name}</div></div>\n'

    return f"""<!DOCTYPE html>
<html lang="{lang}" dir="{rtl}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Enterprise AI Agent — Setup</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="{font_url}" rel="stylesheet">
<style>
:root {{
  --bg: #0a0c14; --bg2: #111827; --bg3: #1a2236; --bg4: #222d45;
  --accent: #6366f1; --accent2: #4f46e5; --glow: rgba(99,102,241,0.25);
  --success: #22c55e; --danger: #ef4444; --warn: #f59e0b;
  --fg: #e2e8f0; --fg2: #94a3b8; --fg3: #475569;
  --border: #1e2d4a; --border2: #2a3a5c;
  --radius: 14px; --radius-sm: 8px;
  --font: 'Inter', system-ui, sans-serif;
}}
*, *::before, *::after {{ margin:0; padding:0; box-sizing:border-box }}
html {{ font-size: 15px }}
body {{ font-family: var(--font); background: var(--bg); color: var(--fg); min-height:100vh; display:flex; }}

/* Sidebar */
.sidebar {{
  width: 260px; min-width: 260px; background: var(--bg2);
  border-right: 1px solid var(--border); padding: 28px 20px;
  display: flex; flex-direction: column; gap: 8px;
}}
[dir=rtl] .sidebar {{ border-right: none; border-left: 1px solid var(--border); }}
.sidebar-brand {{ padding: 0 4px 24px; border-bottom: 1px solid var(--border); margin-bottom: 16px; }}
.sidebar-brand .logo {{ font-size: 1.1rem; font-weight: 700; color: var(--fg);
  background: linear-gradient(135deg,#6366f1,#a78bfa); -webkit-background-clip: text;
  -webkit-text-fill-color: transparent; }}
.sidebar-brand .sub {{ font-size: 0.7rem; color: var(--fg3); margin-top: 2px; }}
.step-item {{ display: flex; align-items: center; gap: 10px; padding: 9px 10px;
  border-radius: var(--radius-sm); cursor: default; transition: 0.15s; }}
.step-item.active {{ background: rgba(99,102,241,0.12); }}
.step-num {{ width: 26px; height: 26px; border-radius: 50%; display: flex; align-items: center;
  justify-content: center; font-size: 0.72rem; font-weight: 700; flex-shrink: 0;
  background: var(--bg3); color: var(--fg3); border: 1px solid var(--border2); }}
.step-item.done .step-num {{ background: var(--success); color: #fff; border-color: var(--success); }}
.step-item.active .step-num {{ background: var(--accent); color: #fff; border-color: var(--accent); }}
.step-label {{ font-size: 0.82rem; color: var(--fg3); }}
.step-item.active .step-label {{ color: var(--fg); font-weight: 500; }}
.step-item.done .step-label {{ color: var(--fg2); }}

/* Main */
.main {{ flex: 1; display: flex; flex-direction: column; overflow-y: auto; }}
.topbar {{ padding: 20px 40px; border-bottom: 1px solid var(--border);
  background: var(--bg2); display: flex; align-items: center; justify-content: space-between; }}
.topbar h1 {{ font-size: 1.05rem; font-weight: 600; }}
.progress-wrap {{ width: 220px; }}
.progress-bar {{ height: 5px; background: var(--border2); border-radius: 99px; overflow: hidden; margin-top: 4px; }}
.progress-fill {{ height: 100%; background: linear-gradient(90deg, var(--accent), #a78bfa);
  border-radius: 99px; transition: width 0.4s ease; width: {pct}%; }}
.progress-pct {{ font-size: 0.72rem; color: var(--fg3); text-align: right; margin-top: 3px; }}

.content {{ flex: 1; padding: 36px 40px; max-width: 820px; }}

/* Form elements */
.form-group {{ margin-bottom: 22px; }}
.form-group label {{ display: block; font-size: 0.82rem; font-weight: 600;
  color: var(--fg2); margin-bottom: 7px; }}
.form-group .hint {{ font-size: 0.74rem; color: var(--fg3); margin-bottom: 6px; }}
input[type=text], input[type=password], input[type=number], select, textarea {{
  width: 100%; padding: 10px 14px; background: var(--bg3); border: 1px solid var(--border2);
  border-radius: var(--radius-sm); color: var(--fg); font-family: var(--font); font-size: 0.88rem;
  outline: none; transition: 0.15s; }}
input:focus, select:focus, textarea:focus {{ border-color: var(--accent); box-shadow: 0 0 0 3px var(--glow); }}
input::placeholder, textarea::placeholder {{ color: var(--fg3); }}

.radio-group {{ display: flex; flex-direction: column; gap: 8px; }}
.radio-item {{ display: flex; align-items: flex-start; gap: 10px; padding: 12px 14px;
  border: 1px solid var(--border); border-radius: var(--radius-sm); cursor: pointer;
  transition: 0.15s; }}
.radio-item:hover {{ border-color: var(--accent); background: rgba(99,102,241,0.05); }}
.radio-item input[type=radio] {{ margin-top: 2px; accent-color: var(--accent); }}
.radio-item .ri-label {{ font-size: 0.88rem; font-weight: 500; }}
.radio-item .ri-sub {{ font-size: 0.75rem; color: var(--fg3); margin-top: 2px; }}

.toggle-group {{ display: flex; flex-wrap: wrap; gap: 10px; }}
.toggle-item {{ display: flex; align-items: center; gap: 8px; padding: 8px 14px;
  border: 1px solid var(--border); border-radius: var(--radius-sm);
  cursor: pointer; font-size: 0.82rem; transition: 0.15s; }}
.toggle-item:hover {{ border-color: var(--accent); }}
.toggle-item input {{ accent-color: var(--accent); }}

.section-title {{ font-size: 1.15rem; font-weight: 700; color: var(--fg); margin-bottom: 6px; }}
.section-sub {{ font-size: 0.83rem; color: var(--fg2); margin-bottom: 24px; line-height: 1.6; }}

.info-box {{ background: rgba(99,102,241,0.08); border: 1px solid rgba(99,102,241,0.25);
  border-radius: var(--radius-sm); padding: 12px 16px; font-size: 0.82rem; color: var(--fg2);
  margin-bottom: 18px; display: flex; gap: 10px; }}

.btn {{ padding: 11px 24px; border-radius: var(--radius-sm); border: none; cursor: pointer;
  font-family: var(--font); font-size: 0.88rem; font-weight: 600; transition: 0.15s;
  display: inline-flex; align-items: center; gap: 8px; }}
.btn-primary {{ background: var(--accent); color: #fff; }}
.btn-primary:hover {{ background: var(--accent2); transform: translateY(-1px); }}
.btn-secondary {{ background: var(--bg3); color: var(--fg2); border: 1px solid var(--border2); }}
.btn-secondary:hover {{ background: var(--bg4); color: var(--fg); }}
.btn-test {{ background: rgba(99,102,241,0.15); color: var(--accent); border: 1px solid rgba(99,102,241,0.3); padding: 8px 16px; font-size: 0.82rem; }}
.btn-test:hover {{ background: rgba(99,102,241,0.25); }}

.btn-row {{ display: flex; gap: 12px; margin-top: 28px; }}

.test-result {{ padding: 10px 14px; border-radius: var(--radius-sm); font-size: 0.82rem;
  margin-top: 10px; display: none; }}
.test-result.ok {{ background: rgba(34,197,94,0.1); border: 1px solid rgba(34,197,94,0.3); color: #4ade80; }}
.test-result.err {{ background: rgba(239,68,68,0.1); border: 1px solid rgba(239,68,68,0.3); color: #f87171; }}

.code-box {{ background: #0a0c14; border: 1px solid var(--border); border-radius: var(--radius-sm);
  padding: 12px 14px; font-family: 'Consolas', monospace; font-size: 0.8rem; color: #a78bfa;
  word-break: break-all; margin-top: 8px; max-height: 80px; overflow-y: auto; }}

.done-icon {{ font-size: 4rem; text-align: center; margin-bottom: 16px; }}
.done-title {{ font-size: 1.8rem; font-weight: 800; text-align: center;
  background: linear-gradient(135deg,#6366f1,#22c55e); -webkit-background-clip: text;
  -webkit-text-fill-color: transparent; margin-bottom: 12px; }}
.done-card {{ background: var(--bg3); border: 1px solid var(--border); border-radius: var(--radius);
  padding: 20px; margin-bottom: 14px; }}
.done-card h3 {{ font-size: 0.88rem; color: var(--fg2); margin-bottom: 10px; }}
.done-card .kv {{ display: flex; justify-content: space-between; padding: 6px 0;
  border-bottom: 1px solid var(--border); font-size: 0.82rem; }}
.done-card .kv:last-child {{ border-bottom: none; }}
.done-card .kv .k {{ color: var(--fg3); }}
.done-card .kv .v {{ color: var(--accent); font-family: monospace; word-break: break-all; max-width: 60%; }}
.key-box {{ background: var(--bg); border: 1px solid var(--warn); border-radius: var(--radius-sm);
  padding: 14px; font-family: monospace; font-size: 0.82rem; color: var(--warn); word-break: break-all; }}

/* Collapsible sections */
.collapsible {{ border: 1px solid var(--border); border-radius: var(--radius-sm); margin-bottom: 12px; overflow: hidden; }}
.collapsible-header {{ padding: 12px 16px; cursor: pointer; display: flex; align-items: center;
  justify-content: space-between; background: var(--bg3); font-size: 0.88rem; font-weight: 600; }}
.collapsible-header:hover {{ background: var(--bg4); }}
.collapsible-body {{ padding: 16px; display: none; }}
.collapsible-body.open {{ display: block; }}

/* DB discover table */
.discover-table {{ width: 100%; border-collapse: collapse; font-size: 0.78rem; margin-top: 8px; }}
.discover-table th {{ background: var(--bg3); padding: 6px 10px; text-align: left; color: var(--fg2); border-bottom: 1px solid var(--border); }}
.discover-table td {{ padding: 6px 10px; border-bottom: 1px solid var(--border); color: var(--fg3); }}
.discover-table tr:last-child td {{ border-bottom: none; }}

@media (max-width:680px) {{
  .sidebar {{ display: none; }}
  .content {{ padding: 20px; }}
  .topbar {{ padding: 14px 20px; }}
}}
</style>
</head>
<body>
<div class="sidebar">
  <div class="sidebar-brand">
    <div class="logo">⚡ Enterprise AI</div>
    <div class="sub">Setup Wizard v3.0</div>
  </div>
  {sidebar_items}
</div>
<div class="main">
  <div class="topbar">
    <h1>{'✅ Setup Complete' if is_done else step_names[step] if step < len(step_names) else 'Setup'}</h1>
    <div class="progress-wrap">
      <div class="progress-bar"><div class="progress-fill"></div></div>
      <div class="progress-pct">{pct}% complete</div>
    </div>
  </div>
  <div class="content">
    {content}
  </div>
</div>
<script>
function toggleSection(el) {{
  const body = el.nextElementSibling;
  body.classList.toggle('open');
  el.querySelector('.arrow').textContent = body.classList.contains('open') ? '▲' : '▼';
}}
async function testConnection(type, formId, resultId) {{
  const form = document.getElementById(formId);
  const fd = new FormData(form);
  const res = document.getElementById(resultId);
  res.style.display = 'block';
  res.className = 'test-result';
  res.textContent = 'Testing…';
  try {{
    const r = await fetch('/api/test/' + type, {{method:'POST', body: fd}});
    const d = await r.json();
    res.className = 'test-result ' + (d.ok ? 'ok' : 'err');
    res.textContent = d.message;
    if (d.models) res.textContent += '  |  Models: ' + d.models.join(', ');
  }} catch(e) {{ res.className = 'test-result err'; res.textContent = 'Request failed: ' + e; }}
}}
async function buildAndPreviewUrl() {{
  const form = document.getElementById('db-form');
  if (!form) return;
  const fd = new FormData(form);
  const r = await fetch('/api/build-url', {{method:'POST', body: fd}});
  const d = await r.json();
  const el = document.getElementById('url-preview');
  if (el) el.textContent = d.url;
}}
async function discoverSchema() {{
  const form = document.getElementById('db-form');
  const fd = new FormData(form);
  const el = document.getElementById('discover-result');
  el.style.display = 'block';
  el.textContent = 'Discovering tables…';
  try {{
    const r = await fetch('/api/discover/db', {{method:'POST', body: fd}});
    const d = await r.json();
    if (d.ok) {{
      el.textContent = `Found ${{d.tables_count}} tables`;
      const inp = document.getElementById('discovered-tables-json');
      if (inp) inp.value = JSON.stringify(d.tables);
      const tbl = document.getElementById('discover-table-body');
      if (tbl) {{
        tbl.innerHTML = '';
        for (const [name, info] of Object.entries(d.tables).slice(0,20)) {{
          const colCount = Object.keys(info.columns||{{}}).length;
          tbl.innerHTML += `<tr><td>${{name}}</td><td>${{info.table}}</td><td>${{colCount}} cols</td></tr>`;
        }}
        document.getElementById('discover-table-wrap').style.display = 'block';
      }}
    }} else {{
      el.textContent = 'Error: ' + d.message;
    }}
  }} catch(e) {{ el.textContent = 'Request failed'; }}
}}
</script>
</body>
</html>"""


def _step_content(step: int, ctx: dict) -> str:
    lang = ctx["lang"]
    admin_key = ctx["admin_key"]
    user_key  = ctx["user_key"]
    jwt_secret = ctx["jwt_secret"]
    enc_key   = ctx["enc_key"]
    ex_env    = ctx.get("existing_env", {})

    if step == 0:
        return f"""
<div class="section-title">{'Language / اللغة' if lang == 'en' else 'اللغة'}</div>
<div class="section-sub">Choose the language for the setup wizard.</div>
<form method="post" action="/setup?step=0&lang={lang}">
<div class="radio-group">
  <label class="radio-item"><input type="radio" name="language" value="en" {'checked' if lang=='en' else ''}>
    <div><div class="ri-label">English</div><div class="ri-sub">English interface</div></div></label>
  <label class="radio-item"><input type="radio" name="language" value="ar" {'checked' if lang=='ar' else ''}>
    <div><div class="ri-label">العربية</div><div class="ri-sub">واجهة عربية</div></div></label>
</div>
<div class="btn-row">
  <button class="btn btn-primary" type="submit">Next →</button>
</div>
</form>"""

    if step == 1:
        return f"""
<div class="section-title">LLM Provider</div>
<div class="section-sub">Configure the AI language model that powers the agent.</div>
<form id="llm-form" method="post" action="/setup?step=1&lang={lang}">
<div class="form-group">
  <label>Provider</label>
  <select name="provider" onchange="updateDefaults(this.value)">
    <option value="ollama">Ollama (Local — on-premise)</option>
    <option value="openai">OpenAI (GPT-4o, GPT-4o-mini)</option>
    <option value="anthropic">Anthropic Claude</option>
    <option value="google">Google Gemini</option>
    <option value="deepseek">DeepSeek</option>
    <option value="custom">Custom OpenAI-compatible</option>
  </select>
</div>
<div class="form-group">
  <label>Model</label>
  <input type="text" name="model" placeholder="e.g. qwen2.5:7b" value="{ex_env.get('DEFAULT_MODEL','qwen2.5:7b').split(':',1)[-1]}">
</div>
<div class="form-group">
  <label>API Base URL</label>
  <input type="text" name="base_url" id="llm-url" value="{ex_env.get('OPENAI_BASE_URL', ex_env.get('OLLAMA_BASE_URL','http://localhost:11434'))}" placeholder="http://localhost:11434">
  <button type="button" class="btn btn-test" style="margin-top:8px" onclick="testConnection('llm','llm-form','llm-test-res')">⚡ Test Connection</button>
  <div id="llm-test-res" class="test-result"></div>
</div>
<div class="form-group">
  <label>API Key <span style="color:var(--fg3);font-weight:400">(leave blank for Ollama)</span></label>
  <input type="password" name="api_key" placeholder="sk-…  or  leave blank for local models">
</div>
<div class="btn-row">
  <a href="/setup?step=0&lang={lang}" class="btn btn-secondary">← Back</a>
  <button class="btn btn-primary" type="submit">Next →</button>
</div>
</form>
<script>
const defaults = {{
  ollama: ['qwen2.5:7b','http://localhost:11434'],
  openai: ['gpt-4o','https://api.openai.com/v1'],
  anthropic: ['claude-3-5-sonnet-20241022','https://api.anthropic.com/v1'],
  google: ['gemini-1.5-pro','https://generativelanguage.googleapis.com/v1beta'],
  deepseek: ['deepseek-chat','https://api.deepseek.com/v1'],
  custom: ['','http://localhost:11434'],
}};
function updateDefaults(p) {{
  document.querySelector('[name=model]').value = defaults[p][0];
  document.getElementById('llm-url').value = defaults[p][1];
}}
</script>"""

    if step == 2:
        return f"""
<div class="section-title">Agent Identity</div>
<div class="section-sub">Customize how the agent presents itself.</div>
<form method="post" action="/setup?step=2&lang={lang}">
<div class="form-group">
  <label>Agent Name</label>
  <input type="text" name="agent_name" value="Enterprise AI Agent" placeholder="e.g. SmartBot, OnyxAssistant">
</div>
<div class="form-group">
  <label>Personality / System Prompt</label>
  <textarea name="personality" rows="3" placeholder="a professional, concise enterprise assistant">a professional, concise enterprise assistant</textarea>
</div>
<div class="form-group">
  <label>Reply Language</label>
  <select name="reply_language">
    <option value="auto">Auto-detect (follows user's language)</option>
    <option value="en">English only</option>
    <option value="ar">Arabic only</option>
  </select>
</div>
<div class="btn-row">
  <a href="/setup?step=1&lang={lang}" class="btn btn-secondary">← Back</a>
  <button class="btn btn-primary" type="submit">Next →</button>
</div>
</form>"""

    if step == 3:
        return f"""
<div class="section-title">Security & API Keys</div>
<div class="section-sub">API keys protect access to the agent. The admin key has full access; the user key is read-only.</div>
<div class="info-box">⚠ Copy these keys now — they are auto-generated and will not be shown again.</div>
<form method="post" action="/setup?step=3&lang={lang}">
<div class="form-group">
  <label>Admin Key (full access)</label>
  <input type="text" name="admin_key" value="{admin_key}" readonly>
</div>
<div class="form-group">
  <label>User Key (chat & read-only)</label>
  <input type="text" name="user_key" value="{user_key}" readonly>
</div>
<div class="form-group">
  <label>JWT Secret</label>
  <input type="text" name="jwt_secret" value="{jwt_secret}" readonly>
</div>
<div class="form-group">
  <label>Encryption Key</label>
  <input type="text" name="enc_key" value="{enc_key}" readonly>
</div>
<div class="btn-row">
  <a href="/setup?step=2&lang={lang}" class="btn btn-secondary">← Back</a>
  <button class="btn btn-primary" type="submit">Next →</button>
</div>
</form>"""

    if step == 4:
        return f"""
<div class="section-title">Communication Channels</div>
<div class="section-sub">Configure how users interact with the agent.</div>
<form method="post" action="/setup?step=4&lang={lang}">
<div class="form-group">
  <label>Web Dashboard Port</label>
  <input type="number" name="web_port" value="8000" min="1024" max="65535">
</div>
<div class="collapsible">
  <div class="collapsible-header" onclick="toggleSection(this)">
    <span>WhatsApp Integration</span><span class="arrow">▼</span>
  </div>
  <div class="collapsible-body">
    <label class="toggle-item"><input type="checkbox" name="whatsapp_enabled"> Enable WhatsApp</label>
    <div class="form-group" style="margin-top:12px">
      <label>Command Prefix</label>
      <input type="text" name="whatsapp_prefix" value="!" maxlength="3">
    </div>
  </div>
</div>
<div class="collapsible">
  <div class="collapsible-header" onclick="toggleSection(this)">
    <span>Telegram Bot</span><span class="arrow">▼</span>
  </div>
  <div class="collapsible-body">
    <label class="toggle-item"><input type="checkbox" name="telegram_enabled"> Enable Telegram</label>
    <div class="form-group" style="margin-top:12px">
      <label>Bot Token (from @BotFather)</label>
      <input type="password" name="telegram_token" placeholder="123456:ABC-DEF…">
    </div>
  </div>
</div>
<div class="collapsible">
  <div class="collapsible-header" onclick="toggleSection(this)">
    <span>SMTP Email Notifications</span><span class="arrow">▼</span>
  </div>
  <div class="collapsible-body">
    <label class="toggle-item"><input type="checkbox" name="smtp_enabled"> Enable SMTP</label>
    <div class="form-group" style="margin-top:12px">
      <label>SMTP Server</label><input type="text" name="smtp_server" placeholder="smtp.gmail.com">
    </div>
    <div class="form-group">
      <label>Port</label><input type="number" name="smtp_port" value="587">
    </div>
    <div class="form-group">
      <label>Username</label><input type="text" name="smtp_user" placeholder="user@company.com">
    </div>
    <div class="form-group">
      <label>Password / App Password</label><input type="password" name="smtp_pass">
    </div>
    <div class="form-group">
      <label>From Address</label><input type="text" name="smtp_from" placeholder="ai-agent@company.com">
    </div>
  </div>
</div>
<div class="btn-row">
  <a href="/setup?step=3&lang={lang}" class="btn btn-secondary">← Back</a>
  <button class="btn btn-primary" type="submit">Next →</button>
</div>
</form>"""

    if step == 5:
        existing_url = ex_env.get("ACCOUNTING_DB_URL", "")
        return f"""
<div class="section-title">🗄 Database / Accounting Setup</div>
<div class="section-sub">
  Connect the agent to your ERP / accounting database.<br>
  The agent will use a <strong>read-only</strong> connection — never modifies data.<br>
  Supports MSSQL (Onyx Pro), MySQL, PostgreSQL, SQLite.
</div>

<label class="toggle-item" style="margin-bottom:18px">
  <input type="checkbox" id="acct-toggle" name="accounting_enabled" onchange="document.getElementById('db-fields').style.display=this.checked?'block':'none'">
  <span>Enable accounting / database integration</span>
</label>

<div id="db-fields" style="display:none">
<form id="db-form" method="post" action="/setup?step=5&lang={lang}">
  <input type="hidden" name="accounting_enabled" value="on">
  <input type="hidden" id="discovered-tables-json" name="discovered_tables" value="">

  <div class="form-group">
    <label>Internal key (short identifier)</label>
    <input type="text" name="db_key" value="onyxdb" placeholder="onyxdb">
    <div class="hint">Letters, numbers, underscore — used internally</div>
  </div>
  <div class="form-group">
    <label>Display Name</label>
    <input type="text" name="db_display_name" value="OnyxDB" placeholder="Onyx Pro">
  </div>
  <div class="form-group">
    <label>Database Type</label>
    <select name="db_type" onchange="toggleDbFields(this.value)">
      <option value="oracle">Oracle Database (Onyx Pro)</option>
      <option value="mssql">Microsoft SQL Server</option>
      <option value="mysql">MySQL / MariaDB</option>
      <option value="postgresql">PostgreSQL</option>
      <option value="sqlite">SQLite (local file)</option>
    </select>
  </div>

  <div id="db-server-fields">
    <div class="form-group">
      <label>Host / IP Address</label>
      <input type="text" name="host" placeholder="192.168.1.10  or  localhost" onchange="buildAndPreviewUrl()">
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px">
      <div class="form-group">
        <label>Port</label>
        <input type="number" name="port" id="db-port" value="1433" onchange="buildAndPreviewUrl()">
      </div>
      <div class="form-group">
        <label>Database Name</label>
        <input type="text" name="db_name" placeholder="OnyxDB" onchange="buildAndPreviewUrl()">
      </div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px">
      <div class="form-group">
        <label>Username</label>
        <input type="text" name="username" placeholder="ai_agent_reader (read-only)" onchange="buildAndPreviewUrl()">
      </div>
      <div class="form-group">
        <label>Password</label>
        <input type="password" name="password" onchange="buildAndPreviewUrl()">
      </div>
    </div>
    <div class="form-group" id="odbc-row">
      <label>ODBC Driver</label>
      <select name="odbc_driver" onchange="buildAndPreviewUrl()">
        <option value="ODBC Driver 18 for SQL Server">ODBC Driver 18 for SQL Server (recommended)</option>
        <option value="ODBC Driver 17 for SQL Server">ODBC Driver 17 for SQL Server</option>
        <option value="SQL Server">SQL Server (older)</option>
      </select>
    </div>
  </div>
  <div id="db-sqlite-fields" style="display:none">
    <div class="form-group">
      <label>SQLite File Path</label>
      <input type="text" name="sqlite_path" value="data/accounting.db" placeholder="data/accounting.db">
    </div>
  </div>

  <div class="form-group">
    <label>Connection URL Preview</label>
    <div class="code-box" id="url-preview">{existing_url or 'Fill in fields above…'}</div>
    <div class="hint">Or paste a full connection URL directly:</div>
    <input type="text" name="db_url" id="db-url-direct" placeholder="Leave blank to build from fields above" value="{existing_url}">
  </div>

  <div style="display:flex;gap:10px;margin-bottom:12px">
    <button type="button" class="btn btn-test" onclick="testConnection('db','db-form','db-test-res')">⚡ Test Connection</button>
    <button type="button" class="btn btn-test" onclick="discoverSchema()">🔍 Auto-Discover Tables</button>
  </div>
  <div id="db-test-res" class="test-result"></div>
  <div id="discover-result" class="test-result" style="display:none"></div>
  <div id="discover-table-wrap" style="display:none;margin-top:10px">
    <table class="discover-table">
      <thead><tr><th>Logical Name</th><th>Actual Table</th><th>Columns</th></tr></thead>
      <tbody id="discover-table-body"></tbody>
    </table>
  </div>

  <hr style="border-color:var(--border);margin:22px 0">
  <div class="section-title" style="font-size:0.95rem;margin-bottom:8px">Allowed Queries</div>
  <div class="section-sub">Which query types can the agent run?</div>
  <div class="toggle-group">
    {''.join(f'<label class="toggle-item"><input type="checkbox" name="allow_{q}" checked> {q.replace("_"," ").title()}</label>' for q in ["sales_summary","revenue_by_month","top_customers","expenses_summary","invoice_lookup","cash_balance","vendor_balances","sales_by_item"])}
  </div>

  <div class="btn-row">
    <a href="/setup?step=4&lang={lang}" class="btn btn-secondary">← Back</a>
    <button class="btn btn-primary" type="submit">Next →</button>
  </div>
</form>
</div>
<div id="db-skip-form" {'style="display:none"' if existing_url else ''}>
  <form method="post" action="/setup?step=5&lang={lang}">
    <div class="btn-row">
      <a href="/setup?step=4&lang={lang}" class="btn btn-secondary">← Back</a>
      <button class="btn btn-primary" type="submit">Skip & Continue →</button>
    </div>
  </form>
</div>
<script>
function toggleDbFields(t) {{
  document.getElementById('db-server-fields').style.display = t==='sqlite'?'none':'block';
  document.getElementById('db-sqlite-fields').style.display = t==='sqlite'?'block':'none';
  document.getElementById('odbc-row').style.display = t==='mssql'?'block':'none';
  const ports = {{oracle:'1521',mssql:'1433',mysql:'3306',postgresql:'5432'}};
  document.getElementById('db-port').value = ports[t]||'1521';
  buildAndPreviewUrl();
}}
document.getElementById('acct-toggle').addEventListener('change', function() {{
  document.getElementById('db-skip-form').style.display = this.checked ? 'none' : 'block';
}});
</script>"""

    if step == 6:
        perms = [
            ("web_search",           "🔍 Web Search"),
            ("calculator",           "🧮 Calculator"),
            ("get_current_time",     "🕐 Get Current Time"),
            ("read_file",            "📁 File System Read"),
            ("knowledge_rag",        "📚 Knowledge Base (RAG)"),
            ("accounting_tools",     "💼 Accounting / ERP Queries"),
            ("generate_report",      "📊 Report Generation"),
            ("list_reports",         "📋 List Reports"),
            ("search_conversations", "💬 Search Conversation History"),
            ("send_email",           "📧 Send Email Notifications"),
            ("send_webhook",         "🔔 Send Webhook Alerts"),
        ]
        default_on = {"web_search", "calculator", "get_current_time", "knowledge_rag", "generate_report", "list_reports", "search_conversations"}
        items = "".join(
            f'<label class="toggle-item"><input type="checkbox" name="{k}" {"checked" if k in default_on else ""}> {label}</label>'
            for k, label in perms
        )
        return f"""
<div class="section-title">Permissions</div>
<div class="section-sub">Control which capabilities the agent is allowed to use.</div>
<form method="post" action="/setup?step=6&lang={lang}">
<div class="toggle-group">{items}</div>
<div class="btn-row">
  <a href="/setup?step=5&lang={lang}" class="btn btn-secondary">← Back</a>
  <button class="btn btn-primary" type="submit">Next →</button>
</div>
</form>"""

    if step == 7:
        return f"""
<div class="section-title">Review & Finalize</div>
<div class="section-sub">Review your configuration before saving.</div>
<form method="post" action="/setup?step=7&lang={lang}">
<div class="info-box">⚙ Click <strong>Save Configuration</strong> to write .env, config/settings.json, and config/accounting_schema.json</div>
<div class="btn-row">
  <a href="/setup?step=6&lang={lang}" class="btn btn-secondary">← Back</a>
  <button class="btn btn-primary" type="submit">💾 Save Configuration</button>
</div>
</form>"""

    # Done (step >= 8)
    return f"""
<div class="done-icon">🎉</div>
<div class="done-title">Setup Complete!</div>
<div class="section-sub" style="text-align:center;margin-bottom:24px">
  Your Enterprise AI Agent is configured and ready to run.
</div>
<div class="done-card">
  <h3>Files Written</h3>
  <div class="kv"><span class="k">.env</span><span class="v">API keys, model, DB URL</span></div>
  <div class="kv"><span class="k">config/settings.json</span><span class="v">Agent settings &amp; permissions</span></div>
  <div class="kv"><span class="k">config/accounting_schema.json</span><span class="v">Database schema mappings</span></div>
</div>
<div class="done-card">
  <h3>Next Steps</h3>
  <div class="kv"><span class="k">Start agent</span><span class="v">python start.py</span></div>
  <div class="kv"><span class="k">Dashboard</span><span class="v">http://localhost:8000</span></div>
  <div class="kv"><span class="k">API Docs</span><span class="v">http://localhost:8000/docs</span></div>
</div>
<div style="margin-top:20px;text-align:center">
  <a href="/setup" class="btn btn-secondary">Run Setup Again</a>
</div>"""
