"""
Accounting connector — read-only access to ERP/accounting databases.

Designed for **Onyx Pro** (YemenSoft) but works with any SQL-based ERP.
Table/column names are NOT hardcoded — loaded from a schema config file
generated by the discovery tool or written manually.

SECURITY: enforces read-only queries (SELECT/WITH only).
Use a dedicated DB user with SELECT-only permissions in production.
"""
from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from typing import Any

try:
    from sqlalchemy import create_engine, text, inspect
    from sqlalchemy.engine import Engine
    HAS_SQLALCHEMY = True
except ImportError:
    HAS_SQLALCHEMY = False

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMA_CONFIG_PATH = os.getenv("ACCOUNTING_SCHEMA_PATH",
                               os.path.join(ROOT, "config", "accounting_schema.json"))
READONLY_PATTERN = re.compile(r"^\s*(?:--[^\n]*\n\s*)*(SELECT|WITH)\b", re.IGNORECASE | re.DOTALL)
# Reject queries that contain semicolons (multi-statement) to prevent second-statement injection
HAS_SEMICOLON = re.compile(r";\s*\S", re.DOTALL)

# ─── Default schema (Onyx Pro - adjust per installation) ─────────
DEFAULT_SCHEMA = {
    "version": 1,
    "name": "Onyx Pro (default)",
    "tables": {
        "sales_invoices": {
            "table": "SalesInvoices",
            "alias": "inv",
            "columns": {
                "id": "InvoiceID",
                "number": "InvoiceNo",
                "date": "InvoiceDate",
                "net_total": "NetTotal",
                "tax": "TaxAmount",
                "discount": "DiscountAmount",
                "status": "Status",
                "customer_id": "CustomerID",
            },
        },
        "customers": {
            "table": "Customers",
            "alias": "c",
            "columns": {
                "id": "CustomerID",
                "name": "CustomerName",
                "code": "CustomerCode",
                "phone": "Phone",
                "email": "Email",
            },
        },
        "accounts": {
            "table": "Accounts",
            "alias": "a",
            "columns": {
                "id": "AccountID",
                "name": "AccountName",
                "code": "AccountCode",
                "type": "AccountType",
            },
        },
        "journal_entries": {
            "table": "JournalEntries",
            "alias": "j",
            "columns": {
                "id": "EntryID",
                "date": "EntryDate",
                "account_id": "AccountID",
                "debit": "Debit",
                "credit": "Credit",
                "description": "Description",
                "reference": "ReferenceNo",
            },
        },
        "purchase_invoices": {
            "table": "PurchaseInvoices",
            "alias": "p",
            "columns": {
                "id": "PurchaseID",
                "number": "PurchaseNo",
                "date": "PurchaseDate",
                "net_total": "NetTotal",
                "tax": "TaxAmount",
                "status": "Status",
                "vendor_id": "VendorID",
            },
        },
        "vendors": {
            "table": "Vendors",
            "alias": "v",
            "columns": {
                "id": "VendorID",
                "name": "VendorName",
                "code": "VendorCode",
            },
        },
        "items": {
            "table": "Items",
            "alias": "i",
            "columns": {
                "id": "ItemID",
                "name": "ItemName",
                "code": "ItemCode",
                "category": "Category",
                "unit_price": "UnitPrice",
            },
        },
    },
}

# ─── Query templates (use {table.X.col} syntax) ──────────────────
QUERY_TEMPLATES: dict[str, str] = {
    "sales_summary": """
        SELECT
            COUNT(DISTINCT {sales_invoices.col.number}) AS invoice_count,
            SUM({sales_invoices.col.net_total}) AS total_sales,
            SUM({sales_invoices.col.tax}) AS total_tax,
            SUM({sales_invoices.col.discount}) AS total_discount
        FROM {sales_invoices.table} {sales_invoices.alias}
        WHERE {sales_invoices.alias}.{sales_invoices.col.date} BETWEEN :start AND :end
          AND {sales_invoices.alias}.{sales_invoices.col.status} = 'Posted'
    """,
    "revenue_by_month": """
        SELECT
            FORMAT({sales_invoices.alias}.{sales_invoices.col.date}, 'yyyy-MM') AS month,
            SUM({sales_invoices.alias}.{sales_invoices.col.net_total}) AS revenue
        FROM {sales_invoices.table} {sales_invoices.alias}
        WHERE {sales_invoices.alias}.{sales_invoices.col.date} BETWEEN :start AND :end
          AND {sales_invoices.alias}.{sales_invoices.col.status} = 'Posted'
        GROUP BY FORMAT({sales_invoices.alias}.{sales_invoices.col.date}, 'yyyy-MM')
        ORDER BY month
    """,
    "top_customers": """
        SELECT TOP (:limit)
            {customers.alias}.{customers.col.name} AS customer_name,
            SUM({sales_invoices.alias}.{sales_invoices.col.net_total}) AS total_sales,
            COUNT(DISTINCT {sales_invoices.alias}.{sales_invoices.col.number}) AS invoices
        FROM {sales_invoices.table} {sales_invoices.alias}
        JOIN {customers.table} {customers.alias}
            ON {customers.alias}.{customers.col.id} = {sales_invoices.alias}.{sales_invoices.col.customer_id}
        WHERE {sales_invoices.alias}.{sales_invoices.col.date} BETWEEN :start AND :end
          AND {sales_invoices.alias}.{sales_invoices.col.status} = 'Posted'
        GROUP BY {customers.alias}.{customers.col.name}
        ORDER BY total_sales DESC
    """,
    "expenses_summary": """
        SELECT
            {accounts.alias}.{accounts.col.name} AS account_name,
            SUM({journal_entries.alias}.{journal_entries.col.debit}
                - {journal_entries.alias}.{journal_entries.col.credit}) AS total
        FROM {journal_entries.table} {journal_entries.alias}
        JOIN {accounts.table} {accounts.alias}
            ON {accounts.alias}.{accounts.col.id} = {journal_entries.alias}.{journal_entries.col.account_id}
        WHERE {accounts.alias}.{accounts.col.type} IN ('Expense', 'مصروف')
          AND {journal_entries.alias}.{journal_entries.col.date} BETWEEN :start AND :end
        GROUP BY {accounts.alias}.{accounts.col.name}
        ORDER BY total DESC
    """,
    "invoice_lookup": """
        SELECT
            {sales_invoices.alias}.{sales_invoices.col.number} AS invoice_no,
            {sales_invoices.alias}.{sales_invoices.col.date} AS invoice_date,
            {sales_invoices.alias}.{sales_invoices.col.net_total} AS total,
            {sales_invoices.alias}.{sales_invoices.col.status} AS status,
            {customers.alias}.{customers.col.name} AS customer_name
        FROM {sales_invoices.table} {sales_invoices.alias}
        JOIN {customers.table} {customers.alias}
            ON {customers.alias}.{customers.col.id} = {sales_invoices.alias}.{sales_invoices.col.customer_id}
        WHERE {sales_invoices.alias}.{sales_invoices.col.number} = :invoice_no
    """,
    "cash_balance": """
        SELECT
            {accounts.alias}.{accounts.col.name} AS account_name,
            SUM({journal_entries.alias}.{journal_entries.col.debit}
                - {journal_entries.alias}.{journal_entries.col.credit}) AS balance
        FROM {journal_entries.table} {journal_entries.alias}
        JOIN {accounts.table} {accounts.alias}
            ON {accounts.alias}.{accounts.col.id} = {journal_entries.alias}.{journal_entries.col.account_id}
        WHERE {accounts.alias}.{accounts.col.type} IN ('Cash', 'Bank', 'نقد', 'بنك')
        GROUP BY {accounts.alias}.{accounts.col.name}
    """,
    "vendor_balances": """
        SELECT
            {vendors.alias}.{vendors.col.name} AS vendor_name,
            SUM({purchase_invoices.alias}.{purchase_invoices.col.net_total}) AS total_purchases
        FROM {purchase_invoices.table} {purchase_invoices.alias}
        JOIN {vendors.table} {vendors.alias}
            ON {vendors.alias}.{vendors.col.id} = {purchase_invoices.alias}.{purchase_invoices.col.vendor_id}
        WHERE {purchase_invoices.alias}.{purchase_invoices.col.date} BETWEEN :start AND :end
          AND {purchase_invoices.alias}.{purchase_invoices.col.status} = 'Posted'
        GROUP BY {vendors.alias}.{vendors.col.name}
        ORDER BY total_purchases DESC
    """,
    "sales_by_item": """
        SELECT
            {items.alias}.{items.col.name} AS item_name,
            SUM(sid.Quantity) AS qty_sold,
            SUM(sid.LineTotal) AS total
        FROM SalesInvoiceDetails sid
        JOIN {items.table} {items.alias}
            ON {items.alias}.{items.col.id} = sid.ItemID
        JOIN {sales_invoices.table} {sales_invoices.alias}
            ON {sales_invoices.alias}.{sales_invoices.col.id} = sid.InvoiceID
        WHERE {sales_invoices.alias}.{sales_invoices.col.date} BETWEEN :start AND :end
          AND {sales_invoices.alias}.{sales_invoices.col.status} = 'Posted'
        GROUP BY {items.alias}.{items.col.name}
        ORDER BY total DESC
    """,
}


@dataclass
class SchemaConfig:
    """Loaded from config/accounting_schema.json — table/column mappings."""
    version: int = 1
    name: str = "Onyx Pro"
    tables: dict = field(default_factory=lambda: DEFAULT_SCHEMA["tables"])
    query_aliases: dict[str, str] = field(default_factory=dict)

    @classmethod
    def load(cls, path: str = SCHEMA_CONFIG_PATH) -> "SchemaConfig":
        if not os.path.exists(path):
            return cls()
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
            # Merge with defaults so new keys are always present
            tables = dict(DEFAULT_SCHEMA["tables"])
            for key, val in data.get("tables", {}).items():
                if key in tables:
                    tables[key].update(val)
                else:
                    tables[key] = val
            return cls(
                version=data.get("version", 1),
                name=data.get("name", "Custom"),
                tables=tables,
                query_aliases=data.get("query_aliases", {}),
            )
        except (json.JSONDecodeError, OSError):
            return cls()

    def save(self, path: str = SCHEMA_CONFIG_PATH) -> None:
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        # Strip alias from saved config (it's auto-derived)
        clean = {"version": self.version, "name": self.name,
                 "tables": {k: {kk: vv for kk, vv in v.items() if kk != "alias"}
                            for k, v in self.tables.items()},
                 "query_aliases": self.query_aliases}
        with open(path, "w", encoding="utf-8") as f:
            json.dump(clean, f, indent=2, ensure_ascii=False)

    def render_query(self, template: str) -> str:
        """Replace {table.X.col} / {table.alias} / {table.table} placeholders."""
        result = template
        for tb_name, tb in self.tables.items():
            alias = tb.get("alias", tb_name[:1])
            result = result.replace(f"{{{tb_name}.alias}}", alias)
            result = result.replace(f"{{{tb_name}.table}}", tb["table"])
            for col_key, col_val in tb.get("columns", {}).items():
                result = result.replace(f"{{{tb_name}.col.{col_key}}}", col_val)
        return result

    def get_resolved_queries(self) -> dict[str, str]:
        return {k: self.render_query(v) for k, v in QUERY_TEMPLATES.items()}


# ─── Schema Discovery ─────────────────────────────────────────────
DISCOVERY_HEURISTICS = {
    "sales_invoices": {
        "keywords": ["sales", "invoice", "sale", "فاتورة", "مبيعات", "بيع"],
        "columns": {
            "number": ["invoiceno", "invoice_no", "inv_no", "invno", "number", "رقم_الفاتورة"],
            "date": ["invoicedate", "invoice_date", "inv_date", "date", "تاريخ"],
            "net_total": ["nettotal", "net_total", "total", "total_amount", "amount", "net", "الإجمالي", "الصافي"],
            "tax": ["taxamount", "tax_amount", "tax", "ضريبة"],
            "status": ["status", "حالة", "state"],
            "customer_id": ["customerid", "customer_id", "cust_id", "رقم_العميل"],
        },
    },
    "customers": {
        "keywords": ["customer", "client", "عميل", "زبون", "عملاء"],
        "columns": {
            "id": ["customerid", "customer_id", "cust_id", "id", "رقم_العميل"],
            "name": ["customername", "customer_name", "cust_name", "name", "اسم"],
            "code": ["customercode", "customer_code", "cust_code", "code", "كود"],
        },
    },
    "accounts": {
        "keywords": ["account", "chart", "حساب", "حسابات", "دليل"],
        "columns": {
            "id": ["accountid", "account_id", "acc_id", "id"],
            "name": ["accountname", "account_name", "acc_name", "name", "اسم_الحساب"],
            "code": ["accountcode", "account_code", "acc_code", "code"],
            "type": ["accounttype", "account_type", "acc_type", "type", "نوع"],
        },
    },
    "journal_entries": {
        "keywords": ["journal", "entry", "voucher", "قيد", "يومية", "قيد_يومية"],
        "columns": {
            "id": ["entryid", "entry_id", "journalid", "voucher_no", "id"],
            "date": ["entrydate", "entry_date", "journal_date", "voucher_date", "date", "تاريخ"],
            "account_id": ["accountid", "account_id", "acc_id", "رقم_الحساب"],
            "debit": ["debit", "مدين", "debit_amount"],
            "credit": ["credit", "دائن", "credit_amount"],
            "description": ["description", "desc", "notes", "بيان", "ملاحظات"],
        },
    },
    "purchase_invoices": {
        "keywords": ["purchase", "purchases", "buy", "شراء", "مشتريات"],
        "columns": {
            "number": ["purchaseno", "purchase_no", "po_no", "number"],
            "date": ["purchasedate", "purchase_date", "date"],
            "net_total": ["nettotal", "total", "amount", "الإجمالي"],
            "status": ["status", "حالة"],
            "vendor_id": ["vendorid", "vendor_id", "supplier_id"],
        },
    },
    "vendors": {
        "keywords": ["vendor", "supplier", "مورد", "موردين"],
        "columns": {
            "id": ["vendorid", "vendor_id", "supplier_id", "id"],
            "name": ["vendorname", "vendor_name", "supplier_name", "name", "اسم_المورد"],
        },
    },
    "items": {
        "keywords": ["item", "product", "صنف", "منتج", "سلعة", "أصناف"],
        "columns": {
            "id": ["itemid", "item_id", "product_id", "id"],
            "name": ["itemname", "item_name", "product_name", "name", "اسم_الصنف"],
            "code": ["itemcode", "item_code", "product_code", "code", "كود"],
            "unit_price": ["unitprice", "unit_price", "price", "سعر"],
        },
    },
}


def discover_schema(db_url: str) -> SchemaConfig:
    """
    Connect to the database and try to identify the schema automatically.
    Returns a SchemaConfig with matched table/column names.
    """
    if not HAS_SQLALCHEMY:
        raise RuntimeError("SQLAlchemy not installed. Run: pip install sqlalchemy pyodbc")

    engine = create_engine(db_url)
    inspector = inspect(engine)
    all_tables = inspector.get_table_names()

    schema = SchemaConfig(version=1, name="Discovered")

    for tb_key, heuristic in DISCOVERY_HEURISTICS.items():
        # Find best matching table
        best_table = _best_match(all_tables, heuristic["keywords"])
        if not best_table:
            continue

        cols = inspector.get_columns(best_table)
        col_names = [c["name"] for c in cols]

        # Map columns
        mapped_cols: dict[str, str] = {}
        for col_key, candidates in heuristic["columns"].items():
            match = _best_match(col_names, candidates)
            if match:
                mapped_cols[col_key] = match

        # Must have at least an id
        if not mapped_cols:
            continue

        schema.tables[tb_key] = {
            "table": best_table,
            "alias": tb_key[:1],
            "columns": mapped_cols,
        }

    return schema


def _best_match(names: list[str], keywords: list[str]) -> str | None:
    """Return the name that best matches one of the keywords (case-insensitive, substring)."""
    name_lower = [(n, n.lower()) for n in names]

    # 1. Exact match
    for name, nl in name_lower:
        if nl in keywords:
            return name

    # 2. Substring match (keyword in name)
    best = None
    best_score = 0
    for name, nl in name_lower:
        for kw in keywords:
            if kw in nl:
                score = len(kw)
                if score > best_score:
                    best_score = score
                    best = name

    if best:
        return best

    # 3. Partial word match
    for name, nl in name_lower:
        for kw in keywords:
            # Check if any word in name matches
            name_words = set(re.split(r"[\s_]", nl))
            kw_words = set(re.split(r"[\s_]", kw))
            if name_words & kw_words:
                return name

    return None


# ─── Connector ────────────────────────────────────────────────────
class AccountingConnector:
    """Runs whitelisted, read-only queries against the accounting database."""

    def __init__(self, db_url: str | None = None, schema: SchemaConfig | None = None):
        self.db_url = db_url or os.getenv("ACCOUNTING_DB_URL", "")
        self.schema = schema or SchemaConfig.load()
        self._engine: Engine | None = None

    @property
    def available(self) -> bool:
        return bool(self.db_url) and HAS_SQLALCHEMY

    @property
    def engine(self) -> Engine:
        if self._engine is None:
            self._engine = create_engine(self.db_url, pool_size=3, pool_recycle=1800)
        return self._engine

    @property
    def resolved_queries(self) -> dict[str, str]:
        return self.schema.get_resolved_queries()

    def test_connection(self) -> dict:
        """Test database connection and return status info."""
        if not self.db_url:
            return {"connected": False, "error": "No database URL configured"}
        if not HAS_SQLALCHEMY:
            return {"connected": False, "error": "SQLAlchemy not installed"}
        try:
            with self.engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            return {"connected": True, "database": str(self.engine.url).split("@")[-1]}
        except Exception as e:
            return {"connected": False, "error": str(e)[:200]}

    def get_schema_info(self) -> dict:
        """Return current schema mapping for display/debug."""
        return {
            "name": self.schema.name,
            "version": self.schema.version,
            "tables": {
                k: {"table": v["table"], "columns": list(v.get("columns", {}).keys())}
                for k, v in self.schema.tables.items()
            },
            "queries": list(self.resolved_queries.keys()),
        }

    def run(self, query_name: str, **params: Any) -> list[dict[str, Any]]:
        if not self.available:
            raise RuntimeError(
                "Accounting database is not configured. "
                "Set ACCOUNTING_DB_URL in .env and ensure SQLAlchemy + pyodbc are installed."
            )
        queries = self.resolved_queries
        sql = queries.get(query_name)
        if sql is None:
            raise ValueError(f"Unknown query '{query_name}'. Available: {list(queries)}")
        if not READONLY_PATTERN.match(sql):
            raise PermissionError("Only read-only (SELECT) queries are allowed.")
        if HAS_SEMICOLON.search(sql):
            raise PermissionError("Multi-statement queries are not allowed.")
        try:
            with self.engine.connect() as conn:
                result = conn.execute(text(sql), params)
                return [dict(row) for row in result.mappings()]
        except Exception as e:
            raise RuntimeError(f"Query '{query_name}' failed: {e}")


# Singleton
connector = AccountingConnector()
