"""
Accounting connector — read-only access to ERP/accounting databases.

Supports MULTIPLE databases (Onyx Pro, Inventory, HR, etc.) managed
in a single schema config file at config/accounting_schema.json.

Designed for **Onyx Pro** (YemenSoft) but works with any SQL-based ERP.
Table/column names are NOT hardcoded — loaded from a schema config file
generated by the discovery tool or written manually.

SECURITY — five independent read-only layers (defense in depth):
  1. Query whitelist: only named QUERY_TEMPLATES can run — never raw SQL
     from the agent, the API, or the user.
  2. Statement check: the rendered SQL must start with SELECT or WITH.
  3. Multi-statement block: a semicolon followed by anything kills the query.
  4. Forbidden keywords: INSERT/UPDATE/DELETE/DROP/ALTER/TRUNCATE/MERGE/
     GRANT/REVOKE/CALL/EXEC anywhere in the SQL kills the query.
  5. Transaction guard: every query runs inside a transaction that is
     ALWAYS rolled back (never committed), and on Oracle the transaction
     is explicitly opened with SET TRANSACTION READ ONLY — so even a bug
     in layers 1–4 physically cannot write to the database.

Still recommended: use a dedicated DB user with SELECT-only permissions
in production (GRANT CONNECT + GRANT SELECT only).

Backward compatible: if ACCOUNTING_DB_URL env var is set without a
config file, or the config file uses the legacy v1 format, the
connector auto-migrates to the new multi-DB format.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from typing import Any

try:
    from sqlalchemy import create_engine, inspect, text
    from sqlalchemy.engine import Engine

    HAS_SQLALCHEMY = True
except ImportError:
    HAS_SQLALCHEMY = False

# Oracle driver (optional)
try:
    import oracledb  # noqa: F401  (driver availability check)

    ORACLE_AVAILABLE = True
except ImportError:
    ORACLE_AVAILABLE = False

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMA_CONFIG_PATH = os.getenv(
    "ACCOUNTING_SCHEMA_PATH", os.path.join(ROOT, "config", "accounting_schema.json")
)
READONLY_PATTERN = re.compile(r"^\s*(?:--[^\n]*\n\s*)*(SELECT|WITH)\b", re.IGNORECASE | re.DOTALL)
# Reject queries that contain semicolons (multi-statement) to prevent second-statement injection
HAS_SEMICOLON = re.compile(r";\s*\S", re.DOTALL)
# Any write/DDL keyword anywhere in the SQL kills the query (belt-and-braces)
FORBIDDEN_SQL = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE|MERGE|GRANT|REVOKE|"
    r"EXEC|EXECUTE|CALL|CREATE|COMMENT|RENAME|LOCK|COMMIT|ROLLBACK)\b",
    re.IGNORECASE,
)

# ─── Default schema (Onyx Pro - used when creating a new DB entry) ─
DEFAULT_SCHEMA = {
    "version": 1,
    "name": "Onyx Pro",
    "tables": {
        "sales_invoices": {
            "table": "SalesInvoices",
            "alias": "inv",
            "columns": {
                "id": "InvoiceID",
                "number": "InvoiceNo",
                "date": "InvoiceDate",
                "net_total": "NetTotal",
                "tax": "TaxAmount",
                "discount": "DiscountAmount",
                "status": "Status",
                "customer_id": "CustomerID",
            },
        },
        "customers": {
            "table": "Customers",
            "alias": "c",
            "columns": {
                "id": "CustomerID",
                "name": "CustomerName",
                "code": "CustomerCode",
                "phone": "Phone",
                "email": "Email",
            },
        },
        "accounts": {
            "table": "Accounts",
            "alias": "a",
            "columns": {
                "id": "AccountID",
                "name": "AccountName",
                "code": "AccountCode",
                "type": "AccountType",
            },
        },
        "journal_entries": {
            "table": "JournalEntries",
            "alias": "j",
            "columns": {
                "id": "EntryID",
                "date": "EntryDate",
                "account_id": "AccountID",
                "debit": "Debit",
                "credit": "Credit",
                "description": "Description",
                "reference": "ReferenceNo",
            },
        },
        "purchase_invoices": {
            "table": "PurchaseInvoices",
            "alias": "p",
            "columns": {
                "id": "PurchaseID",
                "number": "PurchaseNo",
                "date": "PurchaseDate",
                "net_total": "NetTotal",
                "tax": "TaxAmount",
                "status": "Status",
                "vendor_id": "VendorID",
            },
        },
        "vendors": {
            "table": "Vendors",
            "alias": "v",
            "columns": {
                "id": "VendorID",
                "name": "VendorName",
                "code": "VendorCode",
            },
        },
        "items": {
            "table": "Items",
            "alias": "i",
            "columns": {
                "id": "ItemID",
                "name": "ItemName",
                "code": "ItemCode",
                "category": "Category",
                "unit_price": "UnitPrice",
            },
        },
    },
}

# ─── Query templates (use {table.X.col} syntax) ──────────────────
QUERY_TEMPLATES: dict[str, str] = {
    "sales_summary": """
        SELECT
            COUNT(DISTINCT {sales_invoices.col.number}) AS invoice_count,
            SUM({sales_invoices.col.net_total}) AS total_sales,
            SUM({sales_invoices.col.tax}) AS total_tax,
            SUM({sales_invoices.col.discount}) AS total_discount
        FROM {sales_invoices.table} {sales_invoices.alias}
        WHERE {sales_invoices.alias}.{sales_invoices.col.date} BETWEEN :start AND :end
          AND {sales_invoices.alias}.{sales_invoices.col.status} = 'Posted'
    """,
    "revenue_by_month": """
        SELECT
            TO_CHAR({sales_invoices.alias}.{sales_invoices.col.date}, 'YYYY-MM') AS month,
            SUM({sales_invoices.alias}.{sales_invoices.col.net_total}) AS revenue
        FROM {sales_invoices.table} {sales_invoices.alias}
        WHERE {sales_invoices.alias}.{sales_invoices.col.date} BETWEEN :start AND :end
          AND {sales_invoices.alias}.{sales_invoices.col.status} = 'Posted'
        GROUP BY TO_CHAR({sales_invoices.alias}.{sales_invoices.col.date}, 'YYYY-MM')
        ORDER BY month
    """,
    "top_customers": """
        SELECT
            {customers.alias}.{customers.col.name} AS customer_name,
            SUM({sales_invoices.alias}.{sales_invoices.col.net_total}) AS total_sales,
            COUNT(DISTINCT {sales_invoices.alias}.{sales_invoices.col.number}) AS invoices
        FROM {sales_invoices.table} {sales_invoices.alias}
        JOIN {customers.table} {customers.alias}
            ON {customers.alias}.{customers.col.id} = {sales_invoices.alias}.{sales_invoices.col.customer_id}
        WHERE {sales_invoices.alias}.{sales_invoices.col.date} BETWEEN :start AND :end
          AND {sales_invoices.alias}.{sales_invoices.col.status} = 'Posted'
        GROUP BY {customers.alias}.{customers.col.name}
        ORDER BY total_sales DESC
        FETCH FIRST :limit ROWS ONLY
    """,
    "expenses_summary": """
        SELECT
            {accounts.alias}.{accounts.col.name} AS account_name,
            SUM({journal_entries.alias}.{journal_entries.col.debit}
                - {journal_entries.alias}.{journal_entries.col.credit}) AS total
        FROM {journal_entries.table} {journal_entries.alias}
        JOIN {accounts.table} {accounts.alias}
            ON {accounts.alias}.{accounts.col.id} = {journal_entries.alias}.{journal_entries.col.account_id}
        WHERE {accounts.alias}.{accounts.col.type} IN ('Expense', 'مصروف')
          AND {journal_entries.alias}.{journal_entries.col.date} BETWEEN :start AND :end
        GROUP BY {accounts.alias}.{accounts.col.name}
        ORDER BY total DESC
    """,
    "invoice_lookup": """
        SELECT
            {sales_invoices.alias}.{sales_invoices.col.number} AS invoice_no,
            {sales_invoices.alias}.{sales_invoices.col.date} AS invoice_date,
            {sales_invoices.alias}.{sales_invoices.col.net_total} AS total,
            {sales_invoices.alias}.{sales_invoices.col.status} AS status,
            {customers.alias}.{customers.col.name} AS customer_name
        FROM {sales_invoices.table} {sales_invoices.alias}
        JOIN {customers.table} {customers.alias}
            ON {customers.alias}.{customers.col.id} = {sales_invoices.alias}.{sales_invoices.col.customer_id}
        WHERE {sales_invoices.alias}.{sales_invoices.col.number} = :invoice_no
    """,
    "cash_balance": """
        SELECT
            {accounts.alias}.{accounts.col.name} AS account_name,
            SUM({journal_entries.alias}.{journal_entries.col.debit}
                - {journal_entries.alias}.{journal_entries.col.credit}) AS balance
        FROM {journal_entries.table} {journal_entries.alias}
        JOIN {accounts.table} {accounts.alias}
            ON {accounts.alias}.{accounts.col.id} = {journal_entries.alias}.{journal_entries.col.account_id}
        WHERE {accounts.alias}.{accounts.col.type} IN ('Cash', 'Bank', 'نقد', 'بنك')
        GROUP BY {accounts.alias}.{accounts.col.name}
    """,
    "vendor_balances": """
        SELECT
            {vendors.alias}.{vendors.col.name} AS vendor_name,
            SUM({purchase_invoices.alias}.{purchase_invoices.col.net_total}) AS total_purchases
        FROM {purchase_invoices.table} {purchase_invoices.alias}
        JOIN {vendors.table} {vendors.alias}
            ON {vendors.alias}.{vendors.col.id} = {purchase_invoices.alias}.{purchase_invoices.col.vendor_id}
        WHERE {purchase_invoices.alias}.{purchase_invoices.col.date} BETWEEN :start AND :end
          AND {purchase_invoices.alias}.{purchase_invoices.col.status} = 'Posted'
        GROUP BY {vendors.alias}.{vendors.col.name}
        ORDER BY total_purchases DESC
    """,
    "sales_by_item": """
        SELECT
            {items.alias}.{items.col.name} AS item_name,
            SUM(sid.Quantity) AS qty_sold,
            SUM(sid.LineTotal) AS total
        FROM SalesInvoiceDetails sid
        JOIN {items.table} {items.alias}
            ON {items.alias}.{items.col.id} = sid.ItemID
        JOIN {sales_invoices.table} {sales_invoices.alias}
            ON {sales_invoices.alias}.{sales_invoices.col.id} = sid.InvoiceID
        WHERE {sales_invoices.alias}.{sales_invoices.col.date} BETWEEN :start AND :end
          AND {sales_invoices.alias}.{sales_invoices.col.status} = 'Posted'
        GROUP BY {items.alias}.{items.col.name}
        ORDER BY total DESC
    """,
}


@dataclass
class SchemaConfig:
    """Schema mapping for a SINGLE database — table/column mappings."""

    version: int = 1
    name: str = "Onyx Pro"
    db_url: str = ""
    enabled: bool = True
    tables: dict = field(default_factory=lambda: dict(DEFAULT_SCHEMA["tables"]))
    query_aliases: dict[str, str] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict) -> SchemaConfig:
        """Build from a database entry dict (inside the multi-DB config)."""
        tables = dict(DEFAULT_SCHEMA["tables"])
        for key, val in data.get("tables", {}).items():
            if key in tables:
                tables[key].update(val)
            else:
                tables[key] = val
        return cls(
            version=data.get("version", 1),
            name=data.get("name", "Custom"),
            db_url=data.get("db_url", ""),
            enabled=data.get("enabled", True),
            tables=tables,
            query_aliases=data.get("query_aliases", {}),
        )

    def to_dict(self) -> dict:
        """Serialize back to a database entry dict."""
        clean_tables = {
            k: {kk: vv for kk, vv in v.items() if kk != "alias"} for k, v in self.tables.items()
        }
        return {
            "name": self.name,
            "db_url": self.db_url,
            "enabled": self.enabled,
            "tables": clean_tables,
            "query_aliases": self.query_aliases,
        }

    def render_query(self, template: str) -> str:
        """Replace {table.X.col} / {table.alias} / {table.table} placeholders."""
        result = template
        for tb_name, tb in self.tables.items():
            alias = tb.get("alias", tb_name[:1])
            result = result.replace(f"{{{tb_name}.alias}}", alias)
            result = result.replace(f"{{{tb_name}.table}}", tb["table"])
            for col_key, col_val in tb.get("columns", {}).items():
                result = result.replace(f"{{{tb_name}.col.{col_key}}}", col_val)
        return result

    def get_resolved_queries(self) -> dict[str, str]:
        return {k: self.render_query(v) for k, v in QUERY_TEMPLATES.items()}


# ─── Multi-DB config manager ─────────────────────────────────────

CONFIG_DEFAULT = {
    "version": 2,
    "databases": {
        "onyx": {
            "name": "Onyx Pro",
            "db_url": "",
            "enabled": True,
            "tables": {
                k: {kk: vv for kk, vv in v.items() if kk != "alias"}
                for k, v in DEFAULT_SCHEMA["tables"].items()
            },
        },
    },
}


def _load_multi_db_config() -> dict[str, SchemaConfig]:
    """
    Load the schema config file and return a dict of {db_key: SchemaConfig}.

    Backward-compatible with v1 (legacy single-DB format).
    If the config file doesn't exist, checks the ACCOUNTING_DB_URL env var
    for a fallback single DB.
    """
    path = SCHEMA_CONFIG_PATH

    # Case 1: No config file exists — fallback to env var
    if not os.path.exists(path):
        return _fallback_from_env()

    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return _fallback_from_env()

    version = data.get("version", 1)

    # Case 2: Legacy v1 format (single database)
    if version == 1 or "databases" not in data:
        return _migrate_v1(data)

    # Case 3: v2+ multi-DB format
    databases: dict[str, SchemaConfig] = {}
    for db_key, db_data in data.get("databases", {}).items():
        databases[db_key] = SchemaConfig.from_dict(db_data)

    return databases


def _fallback_from_env() -> dict[str, SchemaConfig]:
    """Create a single 'onyx' DB from ACCOUNTING_DB_URL env var."""
    db_url = os.getenv("ACCOUNTING_DB_URL", "")
    if db_url:
        return {
            "onyx": SchemaConfig(
                version=1,
                name="Onyx Pro (from env)",
                db_url=db_url,
                enabled=True,
            )
        }
    return {
        "onyx": SchemaConfig(
            version=1,
            name="Onyx Pro (default)",
            db_url="",
            enabled=False,
        )
    }


def _migrate_v1(data: dict) -> dict[str, SchemaConfig]:
    """Migrate a v1 (legacy single-DB) config to multi-DB format."""
    # Use ACCOUNTING_DB_URL from env if not in config
    db_url = data.get("db_url", "") or os.getenv("ACCOUNTING_DB_URL", "")

    # Build tables with defaults
    tables = dict(DEFAULT_SCHEMA["tables"])
    for key, val in data.get("tables", {}).items():
        if key in tables:
            tables[key].update(val)
        else:
            tables[key] = val

    schema = SchemaConfig(
        version=1,
        name=data.get("name", "Onyx Pro"),
        db_url=db_url,
        enabled=True,
        tables=tables,
        query_aliases=data.get("query_aliases", {}),
    )
    return {"onyx": schema}


def _save_multi_db_config(databases: dict[str, SchemaConfig]) -> None:
    """Save the multi-DB config to disk."""
    db_dict = {}
    for db_key, schema in databases.items():
        db_dict[db_key] = schema.to_dict()

    config = {
        "version": 2,
        "databases": db_dict,
    }
    path = SCHEMA_CONFIG_PATH
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)


# ─── Schema Discovery ─────────────────────────────────────────────
DISCOVERY_HEURISTICS = {
    "sales_invoices": {
        "keywords": ["sales", "invoice", "sale", "فاتورة", "مبيعات", "بيع"],
        "columns": {
            "number": ["invoiceno", "invoice_no", "inv_no", "invno", "number", "رقم_الفاتورة"],
            "date": ["invoicedate", "invoice_date", "inv_date", "date", "تاريخ"],
            "net_total": [
                "nettotal",
                "net_total",
                "total",
                "total_amount",
                "amount",
                "net",
                "الإجمالي",
                "الصافي",
            ],
            "tax": ["taxamount", "tax_amount", "tax", "ضريبة"],
            "status": ["status", "حالة", "state"],
            "customer_id": ["customerid", "customer_id", "cust_id", "رقم_العميل"],
        },
    },
    "customers": {
        "keywords": ["customer", "client", "عميل", "زبون", "عملاء"],
        "columns": {
            "id": ["customerid", "customer_id", "cust_id", "id", "رقم_العميل"],
            "name": ["customername", "customer_name", "cust_name", "name", "اسم"],
            "code": ["customercode", "customer_code", "cust_code", "code", "كود"],
        },
    },
    "accounts": {
        "keywords": ["account", "chart", "حساب", "حسابات", "دليل"],
        "columns": {
            "id": ["accountid", "account_id", "acc_id", "id"],
            "name": ["accountname", "account_name", "acc_name", "name", "اسم_الحساب"],
            "code": ["accountcode", "account_code", "acc_code", "code"],
            "type": ["accounttype", "account_type", "acc_type", "type", "نوع"],
        },
    },
    "journal_entries": {
        "keywords": ["journal", "entry", "voucher", "قيد", "يومية", "قيد_يومية"],
        "columns": {
            "id": ["entryid", "entry_id", "journalid", "voucher_no", "id"],
            "date": ["entrydate", "entry_date", "journal_date", "voucher_date", "date", "تاريخ"],
            "account_id": ["accountid", "account_id", "acc_id", "رقم_الحساب"],
            "debit": ["debit", "مدين", "debit_amount"],
            "credit": ["credit", "دائن", "credit_amount"],
            "description": ["description", "desc", "notes", "بيان", "ملاحظات"],
        },
    },
    "purchase_invoices": {
        "keywords": ["purchase", "purchases", "buy", "شراء", "مشتريات"],
        "columns": {
            "number": ["purchaseno", "purchase_no", "po_no", "number"],
            "date": ["purchasedate", "purchase_date", "date"],
            "net_total": ["nettotal", "total", "amount", "الإجمالي"],
            "status": ["status", "حالة"],
            "vendor_id": ["vendorid", "vendor_id", "supplier_id"],
        },
    },
    "vendors": {
        "keywords": ["vendor", "supplier", "مورد", "موردين"],
        "columns": {
            "id": ["vendorid", "vendor_id", "supplier_id", "id"],
            "name": ["vendorname", "vendor_name", "supplier_name", "name", "اسم_المورد"],
        },
    },
    "items": {
        "keywords": ["item", "product", "صنف", "منتج", "سلعة", "أصناف"],
        "columns": {
            "id": ["itemid", "item_id", "product_id", "id"],
            "name": ["itemname", "item_name", "product_name", "name", "اسم_الصنف"],
            "code": ["itemcode", "item_code", "product_code", "code", "كود"],
            "unit_price": ["unitprice", "unit_price", "price", "سعر"],
        },
    },
}


def discover_schema(db_url: str) -> SchemaConfig:
    """
    Connect to the database and try to identify the schema automatically.
    Returns a SchemaConfig with matched table/column names.
    """
    if not HAS_SQLALCHEMY:
        raise RuntimeError("SQLAlchemy not installed. Run: pip install sqlalchemy pyodbc")

    engine = create_engine(db_url)
    inspector = inspect(engine)
    all_tables = inspector.get_table_names()

    schema = SchemaConfig(version=1, name="Discovered", db_url=db_url)

    for tb_key, heuristic in DISCOVERY_HEURISTICS.items():
        # Find best matching table
        best_table = _best_match(all_tables, heuristic["keywords"])
        if not best_table:
            continue

        cols = inspector.get_columns(best_table)
        col_names = [c["name"] for c in cols]

        # Map columns
        mapped_cols: dict[str, str] = {}
        for col_key, candidates in heuristic["columns"].items():
            match = _best_match(col_names, candidates)
            if match:
                mapped_cols[col_key] = match

        # Must have at least an id
        if not mapped_cols:
            continue

        schema.tables[tb_key] = {
            "table": best_table,
            "alias": tb_key[:1],
            "columns": mapped_cols,
        }

    return schema


def _best_match(names: list[str], keywords: list[str]) -> str | None:
    """Return the name that best matches one of the keywords (case-insensitive, substring)."""
    name_lower = [(n, n.lower()) for n in names]

    # 1. Exact match
    for name, nl in name_lower:
        if nl in keywords:
            return name

    # 2. Substring match (keyword in name)
    best = None
    best_score = 0
    for name, nl in name_lower:
        for kw in keywords:
            if kw in nl:
                score = len(kw)
                if score > best_score:
                    best_score = score
                    best = name

    if best:
        return best

    # 3. Partial word match
    for name, nl in name_lower:
        for kw in keywords:
            name_words = set(re.split(r"[\s_]", nl))
            kw_words = set(re.split(r"[\s_]", kw))
            if name_words & kw_words:
                return name

    return None


# ─── Connector ────────────────────────────────────────────────────
class AccountingConnector:
    """
    Runs whitelisted, read-only queries against MULTIPLE accounting databases.

    Usage:
        connector = AccountingConnector()
        connector.list_databases()      # list configured DBs
        connector.run("onyx", "sales_summary", start="2024-01-01", end="2024-12-31")
        connector.run("inventory", "item_summary")  # another DB

    Backward compatible: methods without a db_name argument default to
    the first configured database.
    """

    def __init__(self):
        self._databases: dict[str, SchemaConfig] = _load_multi_db_config()
        self._engines: dict[str, Engine] = {}

    # ─── Properties ───────────────────────────────────────────

    @property
    def available(self) -> bool:
        """True if at least one database is configured and has a URL."""
        return any(s.db_url and HAS_SQLALCHEMY for s in self._databases.values())

    @property
    def default_db(self) -> str | None:
        """Return the key of the first enabled database, or None."""
        for key, schema in self._databases.items():
            if schema.enabled and schema.db_url:
                return key
        for key, schema in self._databases.items():
            if schema.db_url:
                return key
        return next(iter(self._databases)) if self._databases else None

    # ─── Database management ──────────────────────────────────

    def list_databases(self) -> list[dict]:
        """Return info about all configured databases."""
        result = []
        for db_key, schema in self._databases.items():
            engine_key = f"{db_key}"
            engine = self._engines.get(engine_key)
            connected = engine is not None
            result.append(
                {
                    "key": db_key,
                    "name": schema.name,
                    "enabled": schema.enabled,
                    "has_url": bool(schema.db_url),
                    "connected": connected,
                    "table_count": len(schema.tables),
                    "query_count": len(schema.get_resolved_queries()),
                }
            )
        return result

    def add_database(
        self, db_key: str, name: str, db_url: str, schema: SchemaConfig | None = None
    ) -> SchemaConfig:
        """
        Add a new database to the config. Returns the SchemaConfig.
        If schema is None, uses the default Onyx Pro schema.
        """
        if db_key in self._databases:
            raise ValueError(f"Database key '{db_key}' already exists")

        schema = schema or SchemaConfig(version=1, name=name, db_url=db_url, enabled=True)
        schema.db_url = db_url
        schema.name = name
        self._databases[db_key] = schema
        _save_multi_db_config(self._databases)
        return schema

    def remove_database(self, db_key: str) -> bool:
        """Remove a database from the config. Returns True if removed."""
        if db_key not in self._databases:
            return False
        del self._databases[db_key]
        self._engines.pop(f"{db_key}", None)
        _save_multi_db_config(self._databases)
        return True

    def _get_schema(self, db_name: str | None = None) -> SchemaConfig:
        """Resolve schema for a db_name. Falls back to default DB."""
        key = db_name or self.default_db
        if key is None:
            raise RuntimeError(
                "No accounting database is configured. "
                "Add one via setup or set ACCOUNTING_DB_URL in .env."
            )
        schema = self._databases.get(key)
        if schema is None:
            raise ValueError(f"Database '{key}' not found. Available: {list(self._databases)}")
        return schema

    def _get_engine(self, db_name: str | None = None) -> Engine:
        """Get or create an engine for the given database."""
        key = db_name or self.default_db
        if key is None:
            raise RuntimeError(
                "No accounting database is configured. "
                "Set ACCOUNTING_DB_URL in .env and ensure SQLAlchemy + pyodbc are installed."
            )
        schema = self._get_schema(key)
        if not schema.db_url:
            raise RuntimeError(f"Database '{key}' has no db_url configured.")
        if not HAS_SQLALCHEMY:
            raise RuntimeError(
                "SQLAlchemy not installed. "
                "For SQL Server: pip install sqlalchemy pyodbc\n"
                "For Oracle: pip install sqlalchemy oracledb"
            )

        engine_key = f"{key}"
        if engine_key not in self._engines:
            self._engines[engine_key] = create_engine(schema.db_url, pool_size=2, pool_recycle=1800)
        return self._engines[engine_key]

    # ─── Test / Schema info ───────────────────────────────────

    def test_connection(self, db_name: str | None = None) -> dict:
        """Test database connection and return status info."""
        key = db_name or self.default_db
        if key is None:
            return {"key": None, "connected": False, "error": "No database configured"}
        schema = self._get_schema(key)
        if not schema.db_url:
            return {
                "key": key,
                "name": schema.name,
                "connected": False,
                "error": "No database URL configured",
            }
        if not HAS_SQLALCHEMY:
            return {
                "key": key,
                "name": schema.name,
                "connected": False,
                "error": "SQLAlchemy not installed",
            }
        try:
            engine = self._get_engine(key)
            with engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            host = str(engine.url).split("@")[-1] if "@" in str(engine.url) else str(engine.url)
            return {"key": key, "name": schema.name, "connected": True, "database": host}
        except Exception as e:
            return {"key": key, "name": schema.name, "connected": False, "error": str(e)[:200]}

    def get_schema_info(self, db_name: str | None = None) -> dict:
        """Return current schema mapping for display/debug."""
        schema = self._get_schema(db_name)
        key = db_name or self.default_db
        return {
            "key": key,
            "name": schema.name,
            "version": schema.version,
            "enabled": schema.enabled,
            "has_url": bool(schema.db_url),
            "tables": {
                k: {"table": v["table"], "columns": list(v.get("columns", {}).keys())}
                for k, v in schema.tables.items()
            },
            "queries": list(schema.get_resolved_queries().keys()),
        }

    @property
    def resolved_queries(self) -> dict[str, str]:
        """Return resolved queries for the default database."""
        schema = self._get_schema(None)
        return schema.get_resolved_queries()

    # ─── Query execution ──────────────────────────────────────

    def run(
        self, query_name: str, db_name: str | None = None, **params: Any
    ) -> list[dict[str, Any]]:
        """
        Run a whitelisted read-only query on the specified database.

        Five independent read-only layers (see module docstring):
        whitelist → SELECT/WITH start → no multi-statements →
        no write keywords → transaction that is ALWAYS rolled back
        (Oracle additionally opens with SET TRANSACTION READ ONLY).

        Args:
            query_name: name of the query template to use
            db_name: database key (or None for default)
            **params: query parameters

        Returns: list of dict rows
        """
        key = db_name or self.default_db
        schema = self._get_schema(key)
        engine = self._get_engine(key)

        queries = schema.get_resolved_queries()
        sql = queries.get(query_name)
        if sql is None:
            raise ValueError(
                f"Unknown query '{query_name}' for database '{key}'. " f"Available: {list(queries)}"
            )
        # Layer 2: statement must begin with SELECT / WITH
        if not READONLY_PATTERN.match(sql):
            raise PermissionError("Only read-only (SELECT) queries are allowed.")
        # Layer 3: no multi-statement queries
        if HAS_SEMICOLON.search(sql):
            raise PermissionError("Multi-statement queries are not allowed.")
        # Layer 4: no write/DDL keywords anywhere in the statement
        if FORBIDDEN_SQL.search(sql):
            raise PermissionError(
                "Write or DDL keywords (INSERT/UPDATE/DELETE/DROP/…) are not allowed."
            )
        try:
            # Layer 5: run inside a transaction that is NEVER committed.
            with engine.connect() as conn:
                trans = conn.begin()
                try:
                    if str(engine.url).startswith("oracle"):
                        # Hard guarantee at the Oracle session level: this
                        # transaction physically cannot write to the DB.
                        conn.execute(text("SET TRANSACTION READ ONLY"))
                    result = conn.execute(text(sql), params)
                    rows = [dict(row) for row in result.mappings()]
                finally:
                    trans.rollback()  # always rollback — no write can ever persist
            return rows
        except Exception as e:
            raise RuntimeError(f"Query '{query_name}' on '{key}' failed: {e}") from e

    # ─── Agent-generated SQL (Text-to-SQL) ──────────────────────

    _TABLE_REF = re.compile(r'\b(?:FROM|JOIN)\s+"?\[?([A-Za-z_][\w$.]*)', re.IGNORECASE)

    def db_dialect(self, db_name: str | None = None) -> str:
        """Return the SQL dialect name ('Oracle', 'Microsoft SQL Server', …)."""
        schema = self._get_schema(db_name)
        url = schema.db_url.lower()
        for prefix, name in (
            ("oracle", "Oracle"),
            ("mssql", "Microsoft SQL Server (T-SQL)"),
            ("mysql", "MySQL"),
            ("postgresql", "PostgreSQL"),
            ("sqlite", "SQLite"),
        ):
            if url.startswith(prefix):
                return name
        return "ANSI SQL"

    def describe_schema(self, db_name: str | None = None) -> str:
        """Human/LLM-readable listing of every mapped table and its columns.

        This is the agent's view of the REAL database structure — table and
        column names come from live discovery (or the schema config file),
        never hardcoded guesses.
        """
        schema = self._get_schema(db_name)
        lines = [f"Database: {schema.name}  (dialect: {self.db_dialect(db_name)})"]
        for logical, tb in schema.tables.items():
            cols = ", ".join(
                f"{real} [{key}]" for key, real in tb.get("columns", {}).items()
            )
            lines.append(f"- {tb['table']}  (logical: {logical})")
            if cols:
                lines.append(f"    columns: {cols}")
        return "\n".join(lines)

    def allowed_tables(self, db_name: str | None = None) -> list[str]:
        """Physical table names the agent is allowed to reference."""
        schema = self._get_schema(db_name)
        return [tb["table"] for tb in schema.tables.values()]

    def run_sql(
        self, sql: str, db_name: str | None = None, max_rows: int = 200
    ) -> list[dict[str, Any]]:
        """
        Run an AGENT-GENERATED read-only SELECT (Text-to-SQL path).

        Same five read-only layers as run(), PLUS a sixth: every table
        referenced in FROM/JOIN must be in the discovered-schema whitelist,
        so the agent cannot reach system tables or unmapped data.

        Args:
            sql: the SELECT statement generated by the LLM
            db_name: database key (or None for default)
            max_rows: hard cap on returned rows

        Returns: list of dict rows (at most max_rows)
        """
        key = db_name or self.default_db
        engine = self._get_engine(key)

        sql = sql.strip().rstrip(";").strip()
        # Layer 2: must begin with SELECT / WITH
        if not READONLY_PATTERN.match(sql):
            raise PermissionError("Only read-only (SELECT) queries are allowed.")
        # Layer 3: no multi-statements
        if HAS_SEMICOLON.search(sql):
            raise PermissionError("Multi-statement queries are not allowed.")
        # Layer 4: no write/DDL keywords
        if FORBIDDEN_SQL.search(sql):
            raise PermissionError(
                "Write or DDL keywords (INSERT/UPDATE/DELETE/DROP/…) are not allowed."
            )
        # Layer 6: table whitelist — only tables from the schema config
        allowed = {t.lower() for t in self.allowed_tables(key)}
        refs = {
            m.group(1).split(".")[-1].strip('"[]`').lower()
            for m in self._TABLE_REF.finditer(sql)
        }
        unknown = refs - allowed
        if unknown:
            raise PermissionError(
                f"Query references tables outside the configured schema: {sorted(unknown)}. "
                f"Allowed tables: {sorted(allowed)}"
            )
        try:
            # Layer 5: transaction that is NEVER committed
            with engine.connect() as conn:
                trans = conn.begin()
                try:
                    if str(engine.url).startswith("oracle"):
                        conn.execute(text("SET TRANSACTION READ ONLY"))
                    result = conn.execute(text(sql))
                    rows = [dict(row) for row in result.mappings().fetchmany(max_rows)]
                finally:
                    trans.rollback()
            return rows
        except PermissionError:
            raise
        except Exception as e:
            raise RuntimeError(f"Generated SQL on '{key}' failed: {e}") from e

    # ─── Backward-compat shims ─────────────────────────────────
    # These let old code that calls connector.run("query", key=val) keep working
    # by falling back to default DB.

    def __getattr__(self, name: str):
        # Catch any old-style usage patterns
        raise AttributeError(f"'AccountingConnector' has no attribute '{name}'")


# Singleton
connector = AccountingConnector()
