"""FastAPI application: auth, chat (incl. streaming), knowledge + file upload,
accounting, audit log, dashboard, conversation memory."""
from __future__ import annotations

import datetime
import json
import os
import secrets

from fastapi import Depends, FastAPI, HTTPException, Request, Security, UploadFile
from fastapi.responses import StreamingResponse
from fastapi.security import APIKeyHeader
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

import tools.builtin  # noqa: F401 - registers built-in tools
import tools.accounting  # noqa: F401 - registers accounting/ERP tools
import config_loader
from agent_core.agent import Agent
from orchestrator.agent import OrchestratorAgent
from connectors.accounting import connector as accounting_db
from llm_gateway.gateway import LLMGateway, Message
from memory.store import KnowledgeStore
from memory.conversation import get_store as get_conv_store
from tools.registry import registry

# Apply permission settings from config/settings.json (generated by setup.py):
# remove any tool the wizard disabled so the agent can never call it.
for _tool in list(registry.list()):
    if not config_loader.is_tool_allowed(_tool.name):
        del registry._tools[_tool.name]

# --- Simple role-based auth (replace with SSO/LDAP in production) ---
def _load_dotenv() -> None:
    """Load .env next to the project root so keys always match, however the API was started."""
    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
    if not os.path.exists(path):
        return
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())


_load_dotenv()

API_KEYS: dict[str, str] = {}  # key -> role
_keys_env = os.getenv("API_KEYS")
if not _keys_env:  # build from wizard keys if the launcher didn't pass API_KEYS
    _keys_env = f"admin:{os.getenv('ADMIN_KEY', 'dev-admin-key')},user:{os.getenv('USER_KEY', 'dev-user-key')}"
for entry in _keys_env.split(","):
    role, key = entry.split(":", 1)
    API_KEYS[key] = role

api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def require_role(*roles: str):
    def checker(api_key: str = Security(api_key_header)) -> str:
        role = API_KEYS.get(api_key or "")
        if role is None or (roles and role not in roles):
            raise HTTPException(status_code=403, detail="Invalid or insufficient API key")
        return role
    return checker


# --- Audit log (JSON lines) ---
AUDIT_PATH = os.getenv("AUDIT_LOG_PATH",
                     os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                  "data", "audit.jsonl"))


def audit(event: str, role: str, detail: dict) -> None:
    try:
        os.makedirs(os.path.dirname(AUDIT_PATH) or ".", exist_ok=True)
        entry = {"ts": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                 "event": event, "role": role, **detail}
        with open(AUDIT_PATH, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    except OSError:
        pass


app = FastAPI(
    title="Enterprise AI Agent API — منصة وكيل الذكاء الاصطناعي للمؤسسات",
    description="""منصة وكيل ذكاء اصطناعي للمؤسسات — API للمحادثة، البحث، المحاسبة، إدارة المعرفة، والتقارير.

Enterprise AI Agent Platform — Chat, search, accounting, knowledge management, and reporting API.""",
    version="0.5.0",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
)
gateway = LLMGateway()
store = KnowledgeStore()
conv_store = get_conv_store()


class ChatRequest(BaseModel):
    message: str
    model: str | None = None
    use_knowledge: bool = True
    history: list[dict] | None = None
    session_id: str | None = None
    mode: str = "orchestrator"


class DocRequest(BaseModel):
    title: str
    content: str


async def _with_knowledge(message: str) -> str:
    docs = await store.search(message, gateway=gateway)
    if docs:
        context = "\n\n".join(f"[{d.title}]\n{d.content}" for d in docs)
        return f"Company knowledge context:\n{context}\n\nQuestion: {message}"
    return message


@app.get("/health")
async def health():
    import platform
    import datetime
    import sys
    tools_list = [{"name": t.name, "description": t.description} for t in registry.list()]

    # System info
    sys_info = {
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "uptime": str(datetime.datetime.now() - datetime.datetime.fromtimestamp(os.path.getmtime(
            os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "conversations.db")
        ) if os.path.exists(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "conversations.db")) else 0)) if os.path.exists(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "conversations.db")) else "unknown",
    }

    # Conversations count
    conv_count = len(conv_store.list_sessions(limit=1000))

    # Knowledge docs count
    kb_count = len(store.list())

    # Accounting status
    acc_info = accounting_db.get_schema_info() if accounting_db.available else None
    acc_status = accounting_db.test_connection() if accounting_db.available else None

    return {
        "status": "ok",
        "version": "0.5.0",
        "providers": await gateway.health(),
        "tools_count": len(tools_list),
        "tools": tools_list,
        "accounting": acc_status,
        "accounting_schema": acc_info,
        "conversations": conv_count,
        "knowledge_docs": kb_count,
        "system": sys_info,
        "channels": {
            "whatsapp": os.getenv("WHATSAPP_ENABLED", "false") == "true",
            "telegram": os.getenv("TELEGRAM_ENABLED", "false") == "true",
        }
    }


@app.post("/v1/chat", dependencies=[Depends(require_role("admin", "user"))])
async def chat(req: ChatRequest, role: str = Security(require_role("admin", "user"))):
    # Get or create conversation session
    session_id = conv_store.get_or_create_session(req.session_id)

    # Save user message
    conv_store.save_message(session_id, "user", req.message)

    # Select agent based on mode
    if req.mode == "orchestrator":
        agent = OrchestratorAgent(gateway)
    else:
        agent = Agent(gateway, registry)
    message = req.message
    if req.use_knowledge and config_loader.knowledge_rag_enabled():
        message = await _with_knowledge(req.message)

    # Load history from persistent store (last N exchanges)
    max_mem = int(os.getenv("CHAT_MEMORY", "5"))
    history_raw = conv_store.get_history(session_id, limit=max_mem * 2 + 2)
    history = [Message(**m) for m in history_raw]

    result = await agent.run(message, model=req.model, history=history)

    # Save assistant response
    answer = result.get("answer", "")
    conv_store.save_message(session_id, "assistant", answer)

    # Learn from this exchange
    try:
        from memory.learning import learner
        tools_used = [s.get("tool", "") for s in result.get("steps", [])]
        learner.learn_from_exchange(req.message, answer, tools_used)
        # Auto-learn facts from tool results
        for step in result.get("steps", []):
            result_text = str(step.get("result", ""))
            if "weather" in step.get("tool", ""):
                city = req.message.replace("طقس", "").replace("weather", "").strip().strip("?").strip()
                if city:
                    learner.learn_fact(f"last_weather_check", f"{city}: {result_text[:100]}")
    except Exception:
        pass

    # Auto-title: rename session if still "New conversation"
    sessions = conv_store.list_sessions(limit=1)
    if sessions and sessions[0]["title"] == "New conversation":
        title = req.message[:60] + ("…" if len(req.message) > 60 else "")
        conv_store.rename_session(session_id, title)

    audit("chat", role, {"message": req.message[:500],
                         "session_id": session_id,
                         "tools_used": [s.get("tool") for s in result.get("steps", [])]})
    return {"session_id": session_id, **result}


@app.post("/v1/chat/stream", dependencies=[Depends(require_role("admin", "user"))])
async def chat_stream(req: ChatRequest, role: str = Security(require_role("admin", "user"))):
    # Get or create conversation session
    session_id = conv_store.get_or_create_session(req.session_id)

    # Save user message
    conv_store.save_message(session_id, "user", req.message)

    # Select agent based on mode
    if req.mode == "orchestrator":
        agent = OrchestratorAgent(gateway)
    else:
        agent = Agent(gateway, registry)
    message = req.message
    if req.use_knowledge and config_loader.knowledge_rag_enabled():
        message = await _with_knowledge(req.message)

    max_mem = int(os.getenv("CHAT_MEMORY", "5"))
    history_raw = conv_store.get_history(session_id, limit=max_mem * 2 + 2)
    history = [Message(**m) for m in history_raw]

    audit("chat_stream", role, {"message": req.message[:500], "session_id": session_id})

    async def event_source():
        answer_parts: list[str] = []
        async for event in agent.run_stream(message, model=req.model, history=history):
            if event.get("type") == "token":
                answer_parts.append(event.get("text", ""))
            yield f"data: {json.dumps(event, ensure_ascii=False)}\n\n"
        # Save the full answer
        full = "".join(answer_parts)
        if full:
            conv_store.save_message(session_id, "assistant", full)
            # Learn from streaming exchange
            try:
                from memory.learning import learner
                learner.learn_from_exchange(req.message, full)
            except Exception:
                pass
        # Auto-title for streaming
        sessions = conv_store.list_sessions(limit=1)
        if sessions and sessions[0]["title"] == "New conversation":
            title = req.message[:60] + ("…" if len(req.message) > 60 else "")
            conv_store.rename_session(session_id, title)
        yield f"data: {json.dumps({'type': 'session_id', 'session_id': session_id})}\n\n"

    return StreamingResponse(event_source(), media_type="text/event-stream")


# ---- Conversation management endpoints ----

@app.get("/v1/conversations", dependencies=[Depends(require_role("admin", "user"))])
async def list_conversations():
    return conv_store.list_sessions(limit=50)


@app.get("/v1/conversations/{session_id}", dependencies=[Depends(require_role("admin", "user"))])
async def get_conversation(session_id: str):
    messages = conv_store.get_history(session_id, limit=200)
    sessions = conv_store.list_sessions(limit=200)
    title = "Conversation"
    for s in sessions:
        if s["id"] == session_id:
            title = s["title"]
            break
    return {"session_id": session_id, "title": title, "messages": messages}


@app.delete("/v1/conversations/{session_id}", dependencies=[Depends(require_role("admin"))])
async def delete_conversation(session_id: str):
    ok = conv_store.delete_session(session_id)
    if not ok:
        raise HTTPException(status_code=404, detail="Conversation not found")
    return {"deleted": session_id}


# ---- Existing endpoints ----

@app.get("/v1/tools", dependencies=[Depends(require_role("admin", "user"))])
async def list_tools():
    return [{"name": t.name, "description": t.description, "parameters": t.parameters} for t in registry.list()]


@app.get("/v1/knowledge", dependencies=[Depends(require_role("admin", "user"))])
async def list_docs():
    return [{"id": d.id, "title": d.title, "has_embedding": bool(d.embedding),
             "chars": len(d.content)} for d in store.list()]


@app.post("/v1/knowledge", dependencies=[Depends(require_role("admin"))])
async def add_doc(req: DocRequest):
    doc = store.add(req.title, req.content)
    await store.embed_document(doc, gateway)
    return {"id": doc.id, "title": doc.title, "embedded": bool(doc.embedding)}


def _extract_text(filename: str, data: bytes) -> str:
    name = filename.lower()
    if name.endswith((".txt", ".md", ".csv", ".json", ".log")):
        return data.decode("utf-8", errors="replace")
    if name.endswith(".pdf"):
        from pypdf import PdfReader
        import io
        reader = PdfReader(io.BytesIO(data))
        return "\n".join((p.extract_text() or "") for p in reader.pages)
    if name.endswith(".docx"):
        import docx
        import io
        d = docx.Document(io.BytesIO(data))
        return "\n".join(p.text for p in d.paragraphs)
    raise ValueError(f"Unsupported file type: {filename} (use .txt .md .csv .pdf .docx)")


@app.post("/v1/knowledge/upload", dependencies=[Depends(require_role("admin"))])
async def upload_doc(file: UploadFile, role: str = Security(require_role("admin"))):
    data = await file.read()
    if len(data) > 20 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="File too large (max 20 MB)")
    try:
        text = _extract_text(file.filename or "document", data)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    if not text.strip():
        raise HTTPException(status_code=400, detail="No text could be extracted from this file")
    # split into ~3000-char chunks so retrieval stays focused
    chunks = [text[i:i + 3000] for i in range(0, len(text), 3000)]
    ids = []
    for i, chunk in enumerate(chunks):
        title = f"{file.filename}" + (f" (part {i + 1}/{len(chunks)})" if len(chunks) > 1 else "")
        doc = store.add(title, chunk)
        await store.embed_document(doc, gateway)
        ids.append(doc.id)
    audit("knowledge_upload", role, {"file": file.filename, "chunks": len(ids)})
    return {"file": file.filename, "chunks": len(ids), "ids": ids}


@app.delete("/v1/knowledge/{doc_id}", dependencies=[Depends(require_role("admin"))])
async def delete_doc(doc_id: str):
    if not store.delete(doc_id):
        raise HTTPException(status_code=404, detail="Document not found")
    return {"deleted": doc_id}


@app.post("/v1/admin/rotate-key", dependencies=[Depends(require_role("admin"))])
async def rotate_key(role: str = "user"):
    key = secrets.token_urlsafe(32)
    API_KEYS[key] = role
    return {"api_key": key, "role": role}


@app.get("/v1/admin/audit", dependencies=[Depends(require_role("admin"))])
async def get_audit(limit: int = 100):
    if not os.path.exists(AUDIT_PATH):
        return []
    with open(AUDIT_PATH, encoding="utf-8") as f:
        lines = f.readlines()[-limit:]
    return [json.loads(line) for line in lines if line.strip()]


class AccountingQuery(BaseModel):
    query: str
    params: dict | None = None
    database: str | None = None


class AddDatabaseRequest(BaseModel):
    key: str
    name: str
    db_url: str
    discover: bool = True


class RemoveDatabaseRequest(BaseModel):
    key: str


@app.post("/v1/accounting/query", dependencies=[Depends(require_role("admin"))])
async def accounting_query(req: AccountingQuery, role: str = Security(require_role("admin"))):
    """Run a whitelisted read-only accounting query (admin only)."""
    if req.query not in config_loader.allowed_accounting_queries():
        raise HTTPException(status_code=403, detail=f"Query '{req.query}' is not allowed by settings")
    audit("accounting_query", role, {"query": req.query, "params": req.params, "database": req.database})
    try:
        db_name = req.database or None  # None = default
        return accounting_db.run(req.query, db_name=db_name, **(req.params or {}))
    except (RuntimeError, ValueError, PermissionError) as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.get("/v1/accounting/health", dependencies=[Depends(require_role("admin"))])
async def accounting_health():
    """Test all accounting database connections."""
    dbs = accounting_db.list_databases()
    results = []
    for db in dbs:
        status = accounting_db.test_connection(db["key"])
        try:
            schema = accounting_db.get_schema_info(db["key"])
        except RuntimeError:
            schema = None
        results.append({
            "key": db["key"],
            "name": db["name"],
            "connection": status,
            "schema": schema,
        })
    # Also include backward-compat top-level fields
    default_key = accounting_db.default_db
    default_status = accounting_db.test_connection(default_key)
    default_schema = accounting_db.get_schema_info(default_key) if default_key else {}
    return {
        "databases": results,
        "count": len(results),
        "connection": default_status,
        "schema": default_schema,
        "available": accounting_db.available,
    }


@app.post("/v1/accounting/discover", dependencies=[Depends(require_role("admin"))])
async def accounting_discover(db_url: str = "", name: str = ""):
    """Auto-discover table/column mappings from a live database.

    If db_url is provided, discovers that database and adds it to the config.
    If empty, discovers the first configured database.
    """
    from connectors.accounting import discover_schema, SCHEMA_CONFIG_PATH, _save_multi_db_config

    if not db_url:
        # Use the first configured database
        dbs = accounting_db.list_databases()
        if not dbs:
            raise HTTPException(status_code=400, detail="No databases configured. Provide db_url or configure one first.")
        first = dbs[0]
        schema = accounting_db._get_schema(first["key"])
        db_url = schema.db_url
        if not db_url:
            raise HTTPException(status_code=400, detail=f"Database '{first['key']}' has no db_url set")

    try:
        discovered = discover_schema(db_url)
        discovered.db_url = db_url
        if name:
            discovered.name = name
        # Add as a new database or update the first one
        dbs = accounting_db.list_databases()
        target_key = dbs[0]["key"] if dbs else "onyx"
        try:
            existing = accounting_db._get_schema(target_key)
            discovered.name = existing.name or name or discovered.name
            discovered.db_url = db_url
            # Replace the database in the config
            accounting_db._databases[target_key] = discovered
            _save_multi_db_config(accounting_db._databases)
        except (RuntimeError, ValueError):
            accounting_db.add_database(target_key, name or "Discovered", db_url, discovered)

        audit("accounting_discover", "admin", {"tables": len(discovered.tables), "database": target_key})
        return {"status": "ok", "tables": len(discovered.tables), "saved_to": SCHEMA_CONFIG_PATH,
                "database": target_key,
                "schema": {k: v["table"] for k, v in discovered.tables.items()}}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/v1/accounting/databases", dependencies=[Depends(require_role("admin"))])
async def list_accounting_databases():
    """List all configured accounting databases."""
    return accounting_db.list_databases()


@app.post("/v1/accounting/databases", dependencies=[Depends(require_role("admin"))])
async def add_accounting_database(req: AddDatabaseRequest, role: str = Security(require_role("admin"))):
    """Add a new accounting database to the config."""
    from connectors.accounting import discover_schema
    schema = None
    if req.discover:
        try:
            discovered = discover_schema(req.db_url)
            discovered.name = req.name
            discovered.db_url = req.db_url
            schema = discovered
        except Exception as e:
            raise HTTPException(status_code=400, detail=f"Schema discovery failed: {e}")
    try:
        accounting_db.add_database(req.key, req.name, req.db_url, schema)
        audit("accounting_add_db", role, {"key": req.key, "name": req.name})
        return {"status": "ok", "key": req.key, "name": req.name,
                "tables": len(schema.tables) if schema else 0}
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.delete("/v1/accounting/databases/{db_key}", dependencies=[Depends(require_role("admin"))])
async def remove_accounting_database(db_key: str, role: str = Security(require_role("admin"))):
    """Remove an accounting database from the config."""
    if not accounting_db.remove_database(db_key):
        raise HTTPException(status_code=404, detail=f"Database '{db_key}' not found")
    audit("accounting_remove_db", role, {"key": db_key})
    return {"status": "removed", "key": db_key}


app.mount("/", StaticFiles(directory="dashboard", html=True), name="dashboard")
